---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n-postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.2.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
    global:
      postgresql:
        auth:
          database: n8n
          username: n8n
          existingSecret: n8n-postgres-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: n8n-postgresql-data
