---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgresql-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
