apiVersion: v1
data:
    postgres-password: ENC[AES256_GCM,data:eNXJRPsWUN0J5wn8acoawprK70+B6SaQ,iv:S9jG4lZMJxndH/QXyyF+oCGy7kUD9dwWrZQS/HjAtjg=,tag:mzTgZnHc89HJsuZkWosT4w==,type:str]
    password: ENC[AES256_GCM,data:0nO3EmbuFOvFEdjdbgrSxupVwv+CQ2Fe,iv:sbp1yGnF7crMvlgLLIp+jXyy5N5MwiBaDBRxQAW45/g=,tag:CBr1MJu0NCRhpju6X7aYsw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: n8n-postgres-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhejQzclZ2cFc0aW1jRnhC
            ZHU0cXcxS3hPcXdwM2RiQnBFN3NXV2N5Q0N3CkdJRkJzZTFmNzdvUHMvOXNpT01C
            bHVNVVo5Smx6VUp0R0granQ4QW9CamcKLS0tIDdxWHN4YlhPNE1MTEp0MzdYL1VF
            QTBPTzdwMFFSWUZYYzFzWDNVZUpkOEUKvsd6q2jdktNgNBs2yuemqRqr9KwkWn3T
            L2YfbCkBsn3ru7W9YuOUnyqI326Bom9u2j3ivVkXykvquk5X1z2LQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-20T12:18:18Z"
    mac: ENC[AES256_GCM,data:1JCv1grdTp6omxYXTw/fF2RsJ6BqbCF39FyxGF7uTiNWL9o3R37FG8HuNGa3kLehDWsvgZDWceNA6kD2BcYkuNjVoVBw/a8sK8gPwqSAI0sUtIyuK8KInV6znrrmBLNVemlCCzkXVIy50InJK1BxjqeHZgucqpqJbQ8owqxd1r0=,iv:cmxDBHZAqi9Dp+cuRJ+0MD9WkRcx0RG/JhEkZ97nhmQ=,tag:Z3DhnJCJkUf98Bs7OeOS+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
