---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.3.6.8612
            securityContext:
              runAsUser: 0
    service:
      main:
        controller: main
        ports:
          http:
            port: 7878
    persistence:
      main-config:
        existingClaim: radarr-config
        globalMounts:
          - path: /config
      data:
        existingClaim: data-nfs
        globalMounts:
          - path: /data
      downloads:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /downloads
            subPath: Downloads
    ingress:
      main:
        enabled: true
        hosts:
          - host: "radarr.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ak-outpost-media
                  port: 9000