---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: 8gears-charts
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: n8n-secrets
    config:
      database:
        type: postgresdb
        postgresdb:
          host: n8n-postgresql
          user: n8n
