---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
spec:
  rules:
    - host: "n8n.${PUBLIC_HOSTNAME}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local
                port:
                  number: 9000 
