---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft 
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java23
            env:
              EULA: "TRUE"
              TYPE: "PAPER"
              VERSION: "1.21.4"
              PLUGINS: |
                https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
                https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.3.1/PAPER/ViaVersion-5.3.1.jar
                https://github.com/EssentialsX/Essentials/releases/download/2.21.0/EssentialsX-2.21.0.jar
                https://github.com/EssentialsX/Essentials/releases/download/2.21.0/EssentialsXChat-2.21.0.jar
    service:
      main:
        type: LoadBalancer
        controller: main
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LOCAL_LB_IP}"
          metallb.universe.tf/allow-shared-ip: external-svc
        ports:
          main-udp:
            port: 25565
            protocol: UDP
          main-tcp:
            port: 25565
            protocol: TCP
          other:
            port: 19132
            protocol: UDP
    persistence:
      main-config:
        existingClaim: minecraft-data
        globalMounts:
          - path: /data
