apiVersion: v1
kind: Secret
metadata:
    name: playit-secrets
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:nzZ0Ws8gCMlhpovJh2E+Io2VIxSzq4PrDEESCRS09nFRPTBiWuWTgJtk0w74azjhb9jnjXgdfcfpsrnpCZ9Azw==,iv:MMAxV8zwBX+l6MBTl2WzAOo8PUwkrHrC/hhwaWVaIDI=,tag:avDYml/jo07fOV0bZuWTIA==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc3J3UDBIaG02eDFGc0FW
            WUpwZGpJMFJYckVsY29CVnBEMUtLbUJyZG1NCjE5NEp1elg4Rkx3WU8vcGNVcENR
            OE5kcUV5Nkg5TFlMRW5nTjRVb3Q3c1kKLS0tIEl3bFMzSjdKQjlFZXNsU2hUSHp0
            UklPd0Q5ZFRwbFBBQUoxZngxaWIxTFUK9SN1pFXKf6DQn/LCUx1YkvpRHsFxGsVA
            xQHvXEUokNS3i7nsu1D5Tf1OC4MA6oaMIT7+CrJlRrClWd8qe2ej2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T14:22:09Z"
    mac: ENC[AES256_GCM,data:jlrsZbv/F3fD40BVpo2topMefwWXBgW+3fi6Nl064skpJmISh4eMivTnJdeITFr7/4/SN32/8to5PTHw4pCiPCTcP2S7JSbgXWKduMC9cS2He4SWiupnPCVug0rFJMtIhsG4vs1CIGqHgRzbKDyCWPjYl9jmPh3wbYB2hsJKGks=,iv:SGKfvQ2kakVqCE5pI2dg1GkUlacsnoOClxLeh4HQn8k=,tag:tbQIxyVrZ/bICmKMJpd06A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
