apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:NVjttXiCC4N17Jj5ag9o3Mkub313eczlSN5i93bO1vYrUs1G56DH2NyI9HVKhDyE9AQk0TEDHTxT0uaVDJ35gA==,iv:2g7LNjBiVnawvlAam7jgwBqmFXnVtHMWQsge1D/iS5E=,tag:EJc69alQP0rmKs4H3CoCXg==,type:str]
    #ENC[AES256_GCM,data:fvkR584zbaHArGQYSq/smL9T/Gd7HJojTyW54md/y3OaSVfn4CELh/eBHrPP2xQvmy9Icpyak0KzntHeJUbGgtshOV0dm62vVAxTIO4XXRo=,iv:828JDNKWsqq3noG7ToB7xJ8v8TX87tIzM4e97fuGtVs=,tag:86lgO1IruhANU4ftvkE7/w==,type:comment]
    OPENAI_API_BASE_URL: ENC[AES256_GCM,data:2pvFSu6NVrwkjPYeSbQRvLebltNjQ0BP9Q==,iv:5NIiAZMYDAWm/2SKp/RJ+lpglBXM+Oc7KBdnAe1mTbg=,tag:ehGyMLvHwJLhSOJrZOUduw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Jqlkb5KMszaZTAQVxbtF0oup/z4ptsYur/0=,iv:wZktdGk7N78EpL2lQ2GwXLAL0EDABFEv4vBJXoz/hfw=,tag:M0iiF9RIFiLBjXYGbBBHOw==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPczZIZjVOMG5pUkpkaFZz
            NmZSeHo5SkxrbkRXMFdESjcrS0FEYXBEUEZvCkVOenU2c1lpS29tYXRvbG9LRjBT
            aERoQm9pc25zU1BYTFF6ZnZTYkRlZHcKLS0tIEcxR3NERWFPSG5obm1pV013WS9s
            RjJDQnI3R3F2a215cGI1a1RmM3JPK1UK4ReMuMzVBT/WtAwg8iq7LNfsXvOgs7Sn
            q200cR8n9xZiR4dOWLzWDutNR52ahta25hoAoGKfqdNjKcYVV9o3IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T07:29:29Z"
    mac: ENC[AES256_GCM,data:uVpuelzZbMZHKKqYDCi6ghJ5cLGOp3bkAl5Gu4xwUCRbhO4iLFsXFtexPMkyndYGgRmyln1va4s+n+ishIbDo5EiABLK10LEIljQ0vedO7jEsgDpwMq35KI5iw+6OlmRyRbBHBNKQbZbTGSmehrQ/J5A+n1PD9syBxBtv6yZuU0=,iv:TH+hOHc/keJW8/liKq3M2WX5tbj7gZVI8RsAoyTiQPw=,tag:T/2DOzHNLikQ/QsThxTh0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
