---
 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: wireguard-ingress
   annotations:
     cert-manager.io/cluster-issuer: "letsencrypt-production"
 spec:
   ingressClassName: traefik
   tls:
     - hosts:
         - "wireguard.${PUBLIC_HOSTNAME}"
       secretName: plex-tls
   rules:
     - host: "wg.${PUBLIC_HOSTNAME}"
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: wireguard
                 port:
                   number: 51820