---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.10.5
    defaultPodOptions:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8123
    persistence:
      main-config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config-bak
      config-backup:
        existingClaim: home-assistant-config-backup
        globalMounts:
          - path: /config