---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant 
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.8.1
    hostNetwork: true
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8123
      # bridge:
      #   type: LoadBalancer
      #   externalTrafficPolicy: Cluster
      #   annotations:
      #     metallb.universe.tf/loadBalancerIPs: "${LOCAL_LB_IP}"
      #     metallb.universe.tf/allow-shared-ip: external-svc
      #   ports:
      #     bridge:
      #       enabled: true
      #       port: 21064
      #       protocol: TCP
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        mountPath: /config

