---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant 
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.6.0b6
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8123
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        mountPath: /config

