apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: csi-driver-nfs 
      version: v4.7.0
      sourceRef:
        kind: HelmRepository
        name: csi-nfs-charts
        namespace: flux-system