apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NAS_IP}
  share: /volume2/Media
reclaimPolicy: Retain
volumeBindingMode: Immediate