apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: post-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "10"
  creationTimestamp: "2023-05-09T02:47:01Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    helm.sh/chart: mastodon-1.3.1
  name: mastodon-init
  namespace: social
  resourceVersion: "10746766"
  uid: 24e3e53b-4b5f-4404-a26f-abfdcaaffbd4
spec:
  backoffLimit: 10
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: bfb504c7-7905-4c0d-b55d-18562e86cc06
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: init
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mastodon
        controller-uid: bfb504c7-7905-4c0d-b55d-18562e86cc06
        helm.sh/chart: mastodon-1.3.1
        job-name: mastodon-init
    spec:
      containers:
      - args:
        - /scripts/migrate-and-create-admin.sh
        command:
        - /bin/bash
        - -ec
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MASTODON_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: mastodon-secrets
        - name: MASTODON_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: mastodon-redis
        envFrom:
        - configMapRef:
            name: mastodon-default
        - secretRef:
            name: mastodon-default
        image: docker.io/bitnami/mastodon:4.1.2-debian-11-r10
        imagePullPolicy: IfNotPresent
        name: migrate-and-create-admin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      - args:
        - /scripts/precompile-assets.sh
        command:
        - /bin/bash
        - -ec
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MASTODON_S3_HOSTNAME
          value: mastodon-minio
        - name: MASTODON_S3_PORT_NUMBER
          value: "80"
        - name: MASTODON_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: root-user
              name: mastodon-minio
        - name: MASTODON_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: root-password
              name: mastodon-minio
        envFrom:
        - configMapRef:
            name: mastodon-default
        - secretRef:
            name: mastodon-default
        image: docker.io/bitnami/mastodon:4.1.2-debian-11-r10
        imagePullPolicy: IfNotPresent
        name: mastodon-assets-precompile
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 493
          name: mastodon-init-scripts
        name: scripts
status:
  active: 1
  failed: 1
  ready: 0
  startTime: "2023-05-09T02:47:02Z"
  uncountedTerminatedPods: {}
