---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon-postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.4.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      postgresql:
        auth:
          database: mastodon
          username: mastodon
          existingSecret: mastodon-postgres-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: mastodon-postgresql-data
