apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: actual-budget-rules
  namespace: finance
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: actual-budget.rules
      rules:
        - alert: ActualBudgetServerDown
          annotations:
            description: "The Actual Budget server has been down for more than 5 minutes."
            summary: "Actual Budget server is not available"
          expr: |
            absent(up{job="actual"}) == 1
          for: 5m
          labels:
            severity: critical
            service: actual-budget
            
        - alert: ActualBudgetHighMemoryUsage
          annotations:
            description: "Actual Budget is consuming over 90% of its allocated memory ({{ printf \"%.2f\" $value }}%)."
            summary: "Actual Budget high memory usage detected"
          expr: |
            (container_memory_usage_bytes{container="actual"} / container_spec_memory_limit_bytes{container="actual"} * 100) > 90
          for: 10m
          labels:
            severity: warning
            service: actual-budget
            
        - alert: ActualBudgetHighCPUUsage
          annotations:
            description: "Actual Budget is consuming over 80% of its allocated CPU for over 10 minutes ({{ printf \"%.2f\" $value }}%)."
            summary: "Actual Budget high CPU usage detected"
          expr: |
            (rate(container_cpu_usage_seconds_total{container="actual"}[5m]) / container_spec_cpu_quota{container="actual"} * 100) > 80
          for: 10m
          labels:
            severity: warning
            service: actual-budget
            
        - alert: ActualBudgetTransactionIncreaseAnomaly
          annotations:
            description: "Unusual increase in transactions detected in Actual Budget. Current rate is {{ printf \"%.2f\" $value }} per minute."
            summary: "Unusual transaction activity detected"
          expr: |
            rate(actual_budget_transaction_count[5m]) > (avg_over_time(rate(actual_budget_transaction_count[5m])[1d:5m]) * 3)
          for: 5m
          labels:
            severity: warning
            service: actual-budget
            
        - alert: ActualBudgetStorageNearingCapacity
          annotations:
            description: "Actual Budget persistent storage is {{ printf \"%.2f\" $value }}% full. Consider increasing storage capacity."
            summary: "Actual Budget storage capacity warning"
          expr: |
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"actual-config"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"actual-config"} * 100 > 85
          for: 15m
          labels:
            severity: warning
            service: actual-budget 