---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plaxt
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: plaxt-secrets
    image:
      repository: xanderstrike/goplaxt
      tag: latest
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8000
    persistence:
      config:
        enabled: true
        existingClaim: plaxt-config
        mountPath: /app/keystore
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plaxt.${PUBLIC_HOSTNAME}"
            paths: 
            - path: /
              pathType: Prefix
              service:
                name: plaxt
                port: 9000

