apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  path: ./apps/cert-manager/issuers
  targetNamespace: cert-manager
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system