apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  path: ./apps/cert-manager/app
  targetNamespace: cert-manager
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  path: ./apps/cert-manager/issuers
  targetNamespace: cert-manager
  interval: 10m
  prune: true
  dependsOn:
    - name: cert-manager-app
  sourceRef:
    kind: GitRepository
    name: flux-system