---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoview-postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
    global:
      postgresql:
        auth:
          database: photoview
          username: photoview
          existingSecret: photoview-postgres-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: photoview-postgresql-data
