---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/plex
      tag: 1.31.3
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/allow-shared-ip: external-svc
        ports:
          http:
            enabled: true
            primary: true
            port: 32400
            nodePort: 32400
            protocol: UDP
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
        mountPath: /config
      data:
        enabled: true
        existingClaim: data-nfs
        mountPath: /sorted
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: plex
                  port: 32400
