---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: "1"
    image:
      repository: ghcr.io/linuxserver/plex
      tag: 1.32.0
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
        mountPath: /config
      data:
        enabled: true
        existingClaim: data-nfs
        mountPath: /sortedNFS
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
  - name: port1
    port: 32400
    targetPort: 32400
    protocol: TCP
  selector:
    app: plex
  externalTrafficPolicy: Cluster
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: "${LOCAL_LB_IP_INTEL}"