---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: "1"
    image:
      repository: ghcr.io/linuxserver/plex
      tag: 1.32.2
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LOCAL_LB_IP_INTEL}"
          metallb.universe.tf/allow-shared-ip: intel
        ports:
          http:
            enabled: true
            primary: true
            port: 32400
            protocol: TCP
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
        mountPath: /config
      data:
        enabled: true
        existingClaim: data-nfs
        mountPath: /sortedNFS
