---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- immich
- immich-secondary
- intel-gpu-plugin
- media-shared
- overseerr
- picoshare
- plaxt
- plex
- prowlarr
- radarr
- sabnzbd
- metube
- sonarr
- tautulli
- zipline