---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.94.2
      sourceRef:
        kind: HelmRepository
        name: tailscale-charts
        namespace: flux-system
  values:
    # OAuth credentials from cluster-secrets (substituted by Flux)
    oauth:
      clientId: "${TS_OAUTH_CLIENT_ID}"
      clientSecret: "${TS_OAUTH_CLIENT_SECRET}"
    
    # Override default tags - empty array means no tags
    operatorConfig:
      defaultTags: []
