apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipline
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/diced/zipline
              tag: v3.7.11
            envFrom:
              - secretRef:
                  name: zipline-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    persistence:
      zipline-uploads:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /zipline/uploads
            subPath: Zipline
      public:
        existingClaim: zipline-public
        globalMounts:
          - path: /zipline/public
    ingress:
      main:
        enabled: true
        hosts:
          - host: "share.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: zipline
                  port: 3000