apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipline-public 
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi