---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: v0.107.67
            resources:
              limits: {}
              requests: {}
    defaultPodOptions:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    service:
      main:
        type: LoadBalancer 
        controller: main
        externalTrafficPolicy: Cluster 
        annotations:
            metallb.universe.tf/loadBalancerIPs: "${LOCAL_LB_IP}"
            metallb.universe.tf/allow-shared-ip: external-svc
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
          http:
            port: 3000
            protocol: TCP
    persistence:
      main-config:
        existingClaim: adguard-config
        globalMounts:
          - path: /opt/adguardhome/conf
      data:
        existingClaim: adguard-data
        globalMounts:
          - path: /opt/adguardhome/work
