apiVersion: v1
kind: Secret
metadata:
    name: temporal-secrets
stringData:
    POSTGRES_PWD: ENC[AES256_GCM,data:7h1eeNg7fK9EXIzfy604VSDXcz3DQgb1jvvg4wuVUJLCDwEK8Q68vIEXiY38wsPC,iv:IrVVKYeMNi2MsqfJAIn7miCXquzUKFz6J0VevxnnV6E=,tag:BFU94k841skDbOWgQF4B8Q==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V2V0MUJMRTRBbk9oOXlI
            anJCTzZhYkRHMy91bkwyL3RORVdRdTNQMERFCm5oWHlKa1k1NjEyUTFvRzFpaUhT
            dGhFZTZTNGJyWHdIZjBHdTlqNXRrT2MKLS0tIGJEbDQ4Mk9rSmRuS1UwQ0NsRHlt
            Y0V0V3FuWUpWajNaSHNyV2lmcnU1RkEK5iNKgeI136g0Il2Zam9cEI8XKIyg/6ya
            2R8zvSec+0d2TqvP+mB/+yYz5udAWbuZC2WknDT/1Ke3TMkeOUA30w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T04:55:32Z"
    mac: ENC[AES256_GCM,data:VOHl6JnJMLIFvyuzCqfXFzkW56aBeg4peSPqio6zqUQikr79uRrHtvBM5/HXypiCXQxFrUl/HQ2m1BprNX6W2QMRX7nSzvJutje1u0Q0wEhLlUFNMHZKO7uVET/J/7pGmbvPzV83W+F+o/wsm8JdgNQiqK6MmalNp9kXwac6RCU=,iv:B3hPbjl9VOZNAiwwU2eI9PIi6dUeT8pVTXEDTVux4qk=,tag:MeYbxKiGd7OwqsQNxwLIDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
