apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nfs
  storageClassName: nfs-csi
