apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-download
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-xfs
