apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nfs-scratch
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs-scratch
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: ${NAS_IP}/ClusterScratch##
    volumeAttributes:
      server: ${NAS_IP}
      share: /ClusterScratch