---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  path: ./apps/n8n/app
  targetNamespace: default
  interval: 10m
  prune: true
  dependsOn:
    - name: n8n-db
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: n8n
      namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: n8n-db
  namespace: flux-system
spec:
  path: ./apps/n8n/db
  targetNamespace: default
  interval: 10m
  prune: true
  dependsOn:
    - name: longhorn-app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: n8n-postgresql
      namespace: default
