---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/radarr
      tag: 4.7.5
    service:
      main:
        ports:
          http:
            enabled: true
            port: 7878
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      data:
        enabled: true
        existingClaim: data-nfs
        mountPath: /data
      downloads:
        enabled: true
        existingClaim: media-download
        mountPath: /downloads
    ingress:
      main:
        enabled: true
        hosts:
          - host: "radarr.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ak-outpost-media
                  port: 9000
