apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghost
              tag: 6.0.9
            env:
              url: "https://${PUBLIC_HOSTNAME}" 
              database__client: sqlite3
              database__connection__filename: content/data/ghost.db
              database__useNullAsDefault: true
              database__debug: false
              mail__transport: SMTP
              mail__logger: true
              mail__from: "${MAIL_USER}"
              mail__options__service: Mailgun
              mail__options__host: smtp.mailgun.org
              mail__options__port: 587
              mail__options__secure: false
              mail__options__requireTLS: true
              mail__options__auth__user: "${MAIL_USER}"
              mail__options__auth__pass: "${MAIL_PASS}"
    service:
      main:
        controller: main
        ports:
          http:
            port: 2368
    persistence:
      main-config:
        existingClaim: ghost-data-main
        globalMounts:
          - path: /var/lib/ghost/content