---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
