---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/overseerr
      tag: 2021.12.12
    service:
      main:
        ports:
          http:
            enabled: true
            port: 5055 
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /config
    ingress:
      main:
        enabled: true
        hosts:
          - host: "request.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: overseerr
                  port: 5055
