---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prom
  namespace: flux-system
spec:
  path: ./apps/kube-prom/app
  targetNamespace: tools
  interval: 10m
  prune: true
  dependsOn:
    - name: prom-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: tools
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prom-secrets
  namespace: flux-system
spec:
  path: ./apps/kube-prom/secrets
  targetNamespace: tools
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: prom-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: name
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
            - kind: Secret
              name: prom-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
