apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: linuxserver/changedetection.io
              tag: 0.49.18
            env:
              TZ: "${TIMEZONE}"
              PUID: "1000"
              PGID: "1000"
              BASE_URL: "https://changedetection.${PUBLIC_HOSTNAME}"
    defaultPodOptions:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    service:
      main:
        controller: main
        ports:
          http:
            port: 5000
    persistence:
      main-config:
        existingClaim: changedetection-config
        globalMounts:
          - path: /datastore 