---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plaxt
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: xanderstrike/goplaxt
              tag: latest
            envFrom:
              - secretRef:
                  name: plaxt-secrets
    service:
      main:
        ports:
          http:
            port: 8000
    persistence:
      main-config:
        existingClaim: plaxt-config
        globalMounts:
          - path: /app/keystore
