---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-server
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.20.1
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8266
    persistence:
      data:
        enabled: true
        existingClaim: tdarr-data
        mountPath: /app/data
      media:
        enabled: true
        existingClaim: data-nfs
        mountPath: /media
    ingress:
      main:
        enabled: true
        hosts:
          - host: "tdarr.${PUBLIC_HOSTNAME}"
            paths: 
            - path: /
              pathType: Prefix
              service:
                name: ak-outpost-media
                port: 9000
