apiVersion: v1
kind: Secret
metadata:
    name: picoshare-secrets
stringData:
    PS_SHARED_SECRET: ENC[AES256_GCM,data:UVQFj6ZgmZbDfI+5tyGB8UlogcxI2UVvp2IBSFSEUUs=,iv:wrucogk2f8TL6LNsMw7gn6bnpEUrPI1FipvX5NXUKbg=,tag:beye3Y+YWjidqIxGpsdCmw==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta3NSM000eVZQc3plUUFS
            OE4rY29qTVg2cnJKV2xsTGh0SlJBVW9aMkhjClhaWW5JZFpjMk11ZnkyVHJNQVpM
            V1ZqQ3luK1ZUMEJUaDhObHk1M1pUbUUKLS0tIGFERVNUcnFaZjZQREp4MElIWEoz
            KytzNkpXYm8vbkwrZVBzUmJBbzVPRVkKcKgFIBi3uGJPYLvLcPHLuV5O7aTDdnBb
            yQ7rnM2W+EWTXP/6SYc89c2UYq8E+Vr4e5Z3ysAK5vmMH+5+aB3FBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T07:29:29Z"
    mac: ENC[AES256_GCM,data:7i3SoJVXIZp60Rc/1deZKB5bMTDAIzvcfcAaGp1wmZO9LMCdxVLGaLejV5fOY5yMWbsuLlzxTh0lKixcnJ5MZJ7zk7KPcYzmgmE1P7NpWL0rY2GzWIQZ1eXj7UAWHOWmmzjAgxIDSj4wGQ95wqTsI+M1NfWGfDdXzpuN+niXv1M=,iv:UzNIVhaB5WyaLqVKEOyppHWtbk/MZZ6TobiW6jKI3Hs=,tag:XvQPfex3AGv7tFf8vA3KZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
