---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-ringale
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghost
      tag: 5.60.0
    service:
      main:
        ports:
          http:
            enabled: true
            port: 2386
    persistence:
      config:
        enabled: true
        existingClaim: ghost-data
        mountPath: /var/lib/ghost/content
    ingress:
      main:
        enabled: true
        hosts:
          - host: "SECONDARY_HOSTNAME"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ghost
                  port: 2386

