---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tdarr-node
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: NotIn
                    values:
                      - "true"
    controllers:
      main:
        type: daemonset
        containers:
          main:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.19.01
            env:
              serverIP: tdarr-server-server
    service:
      main:
        controller: main
        enabled: false
    persistence:
      media:
        existingClaim: data-nfs
        path: /media
