---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tdarr-node-hw
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.17.01
            env:
              ffmpegPath: /usr/local/bin/ffmpeg
              serverIP: tdarr-server-server
            resources:
              limits:
                gpu.intel.com/i915: "1"
    service:
      main:
        enabled: false
        controller: main
    persistence:
      media:
        existingClaim: data-nfs
        globalMounts:
          - path: /media
