---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 5m
  chart:
    spec:
      chart: multus-cni
      version: 1.0.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
  # https://gist.github.com/janeczku/ab5139791f28bfba1e0e03cfc2963ecf
    hostCNIBinDir: /var/lib/rancher/k3s/data/current/bin
    hostCNINetDir: /var/lib/rancher/k3s/agent/etc/cni/net.d