---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.21.2-alpine
    service:
      main:
        ports:
          http:
            enabled: true
            port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config
        mountPath: /app/data
    ingress:
      main:
        enabled: true
        hosts:
          - host: "uptimeg.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ak-outpost-media
                  port: 9000
