---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoview
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
        nodeSelector:
          kubernetes.io/arch: amd64
    controllers:
      main:
        containers:
          main:
            image:
              repository: viktorstrate/photoview
              tag: edge
            envFrom:
              - secretRef:
                  name: photoview-secrets
            env:
              PHOTOVIEW_DATABASE_DRIVER: postgres
              PHOTOVIEW_MEDIA_CACHE: /app/cache
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      photos:
        existingClaim: photos-nfs
        globalMounts:
          - path: /photos
      cache:
        existingClaim: photoview-cache
        subMounts:
          - subPath: cache
            mountPath: /app/cache