---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: intel.feature.node.kubernetes.io/gpu
              operator: NotIn
              values:
              - "true"
    env:
      serverIP: tdarr-server-server
    controller:
      type: daemonset
    image:
      repository: haveagitgat/tdarr_node
      tag: 2.14.02
    service:
      main:
        enabled: false
    persistence:
      media:
        enabled: true
        existingClaim: data-nfs
        mountPath: /media
