---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node-hw
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: "1"
    env:
      serverIP: tdarr-server-server
    image:
      repository: haveagitgat/tdarr_node
      tag: 2.00.20
    service:
      main:
        enabled: false
    persistence:
      media:
        enabled: true
        existingClaim: data-nfs
        mountPath: /media
