---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node-hw
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: "1"
    env:
      # By default it uses ffmpeg bundled with the server which doesn't have support for HW encoding/decoding
      ffmpegPath: /usr/local/bin/ffmpeg
      serverIP: tdarr-server-server
    image:
      repository: haveagitgat/tdarr_node
      tag: 2.12.01
    service:
      main:
        enabled: false
    persistence:
      media:
        enabled: true
        existingClaim: data-nfs
        mountPath: /media
