apiVersion: v1
data:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:52eQtoumdfSCAyQKJGpBb6/bnltkij9ZYs0fLGk9g1jNNK+vOUN9G12MYxhKkZPeE4XVOUFIoLbh3Y/VC/ZclaLSQS4=,iv:6Dg41J6PBsDcgSlGMCaZ/GeHPGRnlENztHVlj9KMMko=,tag:2cdJR0RjRqKljgTfn+H0Rw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:0/7tev0g+T09PEGB7UPXH6sH9Vdnc4VPsUEd5vUEeb3+YduPltoG+8nivwUvEQXHZ9NAK16XErRPe3lvkxsAf1TdlkfxW44Tt+L0c0/VgSL7pCwIG4Ywd8i+mLY=,iv:ydJe1sR7yifumJnXr1puE/lYPVEHecUrAYPKKcUhgGA=,tag:6OYEFeQlixm7HEB1Pq/WGw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:LzlLwHNIBukCGbAPaiqrws/vJnXSdxhm,iv:Tts8sw9RSgXiLsyS5+BOXTX507RtdkPl/9LO2ya9A6s=,tag:i38VUQAs6wk1U/A4vxNspg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:orQ4eUAKz3067RscvGHJxVYhLhaIOxq1n5j5Q2FgUGMp+VYGF+s6PleuGNnDVZhJF0jedA==,iv:MLdl1WP1prmTG03xISFR0FLCIEUfPA4gFZgH6o5tlBo=,tag:BwSB2eQ2c85Kn1SY/KX8RQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:rs+lqp/viMglGCI5,iv:gRye2Pnl3djLRkxlpaDgGqcgk0x0J6JyG3FrHAyE3PM=,tag:c9LKw5rY3CO6vLv30TOuNA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:Nsnq1yQ9cJwAERCm,iv:5sQDWp9aRKw+UdP7fijVDzDg69USQbyCZ3fQxuWwdsw=,tag:R5Nkr1c0L7gjHwNkZFn/vA==,type:str]
    AUTHENTIK_SONARR_CLIENT_SECRET: ENC[AES256_GCM,data:oj2gz/55hcuq95KUdPVDFL5TKWCtE5nin5ORDtuBuE4xYsHge2UtpqEilnNxhheWJouQ88TLwXyJnzRK5Qpz58RBNT3RirN+lIytHm0hHlHJcLX91Tj271s91u3pTWIWqX4meSgVLYEj7rgEokWSgvqxLi4LCwEo63W+HFiZhtN7Y+6D0R5w9ZOwfCaboInjJ6kApjxNmC+KAaWoZcH6WjC5ebcvdPGgVyTwqA==,iv:k5X0ZiSjPYMhExOmfNYE15l7mDyxw1SIa0+ucItYV64=,tag:flOpfbEz01heM93x1YPTAQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authentik-secrets
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWk9MQmZRcnkrWFNSUG9S
            cEhLam40RTJ1Z3lKZ2RrbDVwR2xCVTJ3RnlNCmRVejkzcmlPeUFpNTArd0taNTBK
            MlVacTJhOTE0MkdwVElQblFBaGdTVjQKLS0tIGQ4QWtVemV5d0xIR1pOTUtaZk9t
            YlpvOEx6WUJCTWthSk5EVnZJYm5uMUUKFyxbpkQceq3uy76zQ7pTIkBFt3R9ofn7
            4ZvlvVoEeYXzcsPhvh8StagH2lKnET6pa7U64MoEfd/Wzlc29FMC5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T23:30:36Z"
    mac: ENC[AES256_GCM,data:bZ19JKAI+iJzZrssHmIAnnkFslWW697srI1b5Mwz5jfDDZaKnqelVaNEMJd3F81jy5QVM445mA5l/7VX3lKsZNe5TvRw0LSdOf/ubOoLI+6bvjP6e+ZdkFzlOyimgfxX+a5UmbYp/xPBiBL2yjfU8Y3a3wi4hh51UrNBe232cgY=,iv:y0UrSfjSPH+1anLTI33boI2YBVDaCz1yCOBOuIefd8U=,tag:xOOtG+UNTc8/zQrfOhcBmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
