apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      postgresql:
        auth:
          database: authentik
          username: authentik
          existingSecret: authentik-postgres-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: authentik-postgresql-data