apiVersion: v1
data:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:YDFy9noB6Us/ZhKf7q7tdHFf/2ALsldqN4z4it9eQ2r28G/xvrUrlChfHJ2DvL5MzLzz3GssAFg+pcoZpjycDq0Bq00=,iv:Irfvl0Egu6o7NZ153N9NYvQgjtkNewP4RZY+hXu4ezc=,tag:+51Olxevn41TPv0zbKQeow==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:3b810YIISZXrAHc5ttZIuGC10GUnV4vD9e56kFATYV6CfPSm/h4unlAqEZKG4NPtT3xgwjujMa2S/eHl78bKNS65Tpp8G78idIeKzS3VE0NI3moqSVObzl0ll9E=,iv:LGLQd3A+eD3B7C6gQuRFMIAwzIsGZvG/zdpABHjg6+U=,tag:Ny+dkQTxf10yJ3MGxAya6g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:H8kG0nkrSz3V7+zU5lTnEGEZicyS2eJG,iv:75+HddtiKk9AbvnmfllwPtxjmw1J5JL22GprGj8XyxQ=,tag:rpNELydc+peTElKm6B22oQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:Uq07/ncoEBhRrswidv8dkqssWfnqncdAvOEUuKIPDV/uVMSaP8HG2n3Y62FdxTbssL+/Cg==,iv:d1GzCXBM66OGJledCiunQcRqXDHzCoCj2jfLIA8FNDk=,tag:DFJksPDbArW5bFVVDVJALQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:sPFKFcLXAdunhgxR,iv:kD/4HViUq+sdbxdcG0g1+je27uiYMfk5ZKtebBYAxv0=,tag:HNq80IgUkfnap5hTYBf5Ug==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:yUxxp58KlWV1/Yjy,iv:YllJd2u61KbiDnZvqnyoY4ks3U9l5D2b1BvAUKihlt4=,tag:tBis/mU5TEGpokq6o+cjWA==,type:str]
    AUTHENTIK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8k+o/TdvBakF8kl1OuCqxFBlwlHeL9w6VRjqVSUHz/ZzqGBCFfxlP1CAYk7EURAhDK8xBACP1yQMnOdJc7fJ4hrX6po9CRa/TcwMz7SzJaqAE0sjp/iSDMALPrRFYEoAilGfsOdgR4pf1nURM8XB3ciwABHmqIZflA9Djs3ZKOlEWrXKMbpJaYpMsWOvbxjaVEvkgKyMAHuXxzYY1XtkvrjcSt00OHJ3kbAabA==,iv:FECZ+sTOMGpSWwnaZp4YED683KQwroWGsRbPy6xns7M=,tag:7mmI+eEksWDT5mcveZ0JLg==,type:str]
    AUTHENTIK_IMMICH_CLIENT_SECRET: ENC[AES256_GCM,data:DAb8L9QdgmgdL7aRC+O214sgvOFlmEaS74IMLKtFKYhHbmBKAaRujNuxbRA9zth43gNDQz1uus6URHNR2bWq1z2eIA8H4IQrES+Pfm56T5rj3kXlhfrms6/dE7bLDGGPPYT0+yuyG+pKqY7AAT7/zrvCa8hu+DCzwdfl0objp7oDGj59LfP78tjLJzLDJWDKC3rtx/XNRUZN1ArN9e8DcvRG0RdzvcTmUQBymw==,iv:V0XDI0pu4C2UBkci5sAOEwJBnzUYtv7LZo3jhIAZzQg=,tag:X1fFV7I4kJdbWV0v6lwaYw==,type:str]
    AUTHENTIK_HOARDER_CLIENT_SECRET: ENC[AES256_GCM,data:kIx7WL8xyBVj4aakTPyzt5eDEWb5gat+fh3f4/hqbo2DNTkcax4wAA3t/mgpc5l/LiPcFyIm0QY6tsXq2mhNd/5AN1c7gRmZyP89jQ9CbgxMZiv9iazolQhS/+1AAWDwQNBCYDbATlpV5lTVe+HfEE9+jFQrSscluhyCwF/Wy2oNdVE5trZuZAoVPWF/yb5c3RZhi6xoi/c4BgdUdLUunpZnOyqKYD1IjRLkLQ==,iv:deoSJi/Zs6h1Q4WIP7wpqOZSldRNtCOaCfw98ajLrHI=,tag:lYC4/52I+wEfskqNdXJ8wQ==,type:str]
    AUTHENTIK_ACTUAL_CLIENT_SECRET: ENC[AES256_GCM,data:byM8riKfTZV/TU3B4YClfF2uWPIQBSg/NrWl0sSxbJpvYZsfv15VgdNKMSC3HM1E60SwHMHqmsPJhG06DE6bK6C6gZIDzw0TshjWZwcQFdo35UTIlE3TNlMIwg5aoa2QMzV8QmL0f9MjV8KYTemIvy8v0eZ68JYeewJLhm4sDPaBEA4dcxYz3NRUona/6H4qYdjvTyZho3h6JiU15w1YG3oelOhO5it9Q55jiQ==,iv:nGhT0uAwDtQ13VmytZR+cbSO+bIhuELKmm902BJxBv4=,tag:rkd49EmevFAOwtizXC2yiw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authentik-secrets
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaGQzQVVUY1UxdFNFOEMy
            a3dLM2JqazBBMDNkT3JMVlRlSTRiMUVBaHlFCjVYUjgzUEF6cUxkbDBnNzVLNXRZ
            QStPdXF2Nzd5OWtFb1pqajlxdFQ2V28KLS0tIHBYc01iV3FyNzRMcWFCcmp5Snlp
            Y0FLWDBTSUFhZXEvYXd3MHFEa2dMTmsKWCJppa6G2de4ltpY8wVVGms6WXFC4RCg
            N4lB061lTGjlXZ+uB+LN3VF4BOSr0LC4oKnGEo2fylJHRLr911Qn8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T04:19:52Z"
    mac: ENC[AES256_GCM,data:cKuaiHJ+Oe0UgZMiCWzemasjIrPFtlzIC/6O8V7yN9YyGlaEbpmxcdXq61xcpKPYecjrFU6SU+KMROMKQtWFndalZlq2TgIpSxV2PWCkXpGYRUHiXbrzUWi1UvxVsKMtUunh2gpB889YLXlhiBtGGCwvprbMMMr+2iOUKZqoxak=,iv:TM5EbLTgVc53W/9c4WdXpDSbY81bLRrAERvDw2sRefE=,tag:WUUnpKqCDCGrxB9DS+38eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
