apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik 
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.4.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  values:
    global:
      envFrom:
        - secretRef:
            name: authentik-secrets
    authentik:
      error_reporting_enabled: true
      email:
        host: smtp.sendgrid.net
        username: apikey
        use_tls: true
    postgresql:
      enabled: false
    redis:
      enabled: true