apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik 
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.10.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: authentik-secrets
    authentik:
      error_reporting_enabled: true
      email:
        host: smtp.sendgrid.net
        username: apikey
        use_tls: true
    postgresql:
      enabled: false
    redis:
      enabled: true