apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-ingress 
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - "auth.${PUBLIC_HOSTNAME}"
      secretName: auth-tls 
  rules:
    - host: "auth.${PUBLIC_HOSTNAME}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik
                port: 
                  number: 80