apiVersion: v1
data:
    DB_PASS: ENC[AES256_GCM,data:ey4TxLtVGmZps0H2Hljc5o5j9k16us1u9u1cxyB7v58=,iv:knign5ztPXej0j68R1FQb4f7lQCVh6zUb2dYMIZXXEk=,tag:lvtuO42b+G6QQ2LDAVZEWw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:ZKlBJs1zKaH1fLAAYIsZEw69wSzlXncSWXmHdQ==,iv:Efr0fzHiNrGWdQAENHcX2u0S3sAXj1dpnZnFDpeHXUo=,tag:uPKo6dj5AxY9PwHSbpSh0w==,type:str]
    MASTODON_ADMIN_PASSWORD: ENC[AES256_GCM,data:iem0hkBqTISpkMpn,iv:rjOdtUdVi1+GYlye40op2ZSp8WkbKM30eJEu2dUFPEQ=,tag:tSmXEsL3xiTwdwWLvtQ8RA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:57H9J8XshV9NNfIr49szzH6Hygg=,iv:mFauMWU+n3gUsTayRpO1waLbMnqPU459Y671PgHtVrI=,tag:Jc56/S16wkUFsaShZwEVMg==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:xxRn4BkZnHo1axPta8K5Fq2yxbVmIg/D,iv:z3YuX550sB+tnDiphDVllUB9L9OwIiKMsWTsNgN/4SY=,tag:vMC0c7C988FQVLoHUSstgQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:pWarHA53wmOGawGobDJRSbd8jkZe6c35Np0+QxJ8Qc4UDuv5jrhG0OGgamF05W6eBuCt0M0KgDG0DnAm,iv:xyDlIu95L1QH4BdReCYPbr2xye7H604HeJ0K/9LZpUI=,tag:ynSGn3OQbYYtPXJhlQsIyQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:eDdPSaQ8U958dJ0s5JHC0ImnhiNXWBnEfTHfqLUR1WrfNeBzr/YYDDQ3apW8b7vWOvhqzpzSO3KxjavIb8YDA9SFWXKSGUKFztCcYDyn7C7gfT7YJ2Zceu+NF3v6hQG0JvXiGaMmhbZX8r9Sh2rlnHjvOfI=,iv:yzfJtE4kG1DxTI6+bplpnE2xrQMYa9Tjswy6xcfeLMI=,tag:mImXbZ4gNqwp0fjfKnOxhQ==,type:str]
    #ENC[AES256_GCM,data:0/y94HY=,iv:OD5jx5LMdg+FZjbiy+AugNd3HOU1hFyc5k2RLPujpKw=,tag:EPU7Tk+JghFnFkRXqUfO3g==,type:comment]
    root-user: ENC[AES256_GCM,data:WLiKi2MtAVk=,iv:IGk2FghNQjGwuYnHoqBruf5e+pEtyABzSf1dW9/GZcE=,tag:utTq9TqiWw6mmGBYoEP/gg==,type:str]
    root-password: ENC[AES256_GCM,data:4D/Es3FO2R5p3B+WuaJdcA==,iv:BPKJt1EYbO9MevXhB9Uv8sopgN7WUAQZVul79TfPbmM=,tag:LDPSfeCMNjwwuO+3B2r0IQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mastodon-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bCs4QThvS1N1UFlSWmpp
            UStxc1pNeU5ETmlIZ1l2Yy9xRkdoSlJmWmpRCkJJd3Jpb0Q4ZFVjblBuMzRNNHJP
            ckMrSnJBRE92UTgreFVmRHB5b3NhTlUKLS0tIEoxM2hNVEd1TDJGajhva3EyV05s
            eEhOdmhJMFJlbW4zRnJwbUVDdHErYmcKH1yCdGdtSqerlYQN8NCNHSHyph+Mehww
            IcIoRV4dMx+r3i2DZ43qsUnodb+u/GNQeU8UjskWANgQAUEcK2bTuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-13T14:32:28Z"
    mac: ENC[AES256_GCM,data:0ZwapbzVI29acZn+WeS/Ja1OZRh3q8CtnT2NFXaGQKht5QNpOW8Hk3PR3exVg+AWPFIZ0a20Hgpa2y+0BRHDYZHvhWUPfmXy6kG1qXidJFrSp7EYYc0bDH2Ot/Dc5CCfxFMy8O8jMhCiQ8RD/uWfDHF8CWPHRDw2eCey5KUPJsU=,iv:z9WpcTwOHM4jMMuTV/2P+VZ14Pg7+lOh76TqqgZHZlg=,tag:Suo4Efu/r8l6AV2h3NRhKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
