apiVersion: v1
data:
    #ENC[AES256_GCM,data:TatuvRYCAEq2PSXjiq6OTJnHrcfvWvDXIunzSE98/eXQsmJE,iv:kMr53yZt49tm1R5RgI1j64lFiHT7QB0dB4JS/hUOHn8=,tag:YfWZb6ZjxvY1pstpDXQNMA==,type:comment]
    db-password: ENC[AES256_GCM,data:lg3RdOvmtzvymvymD9y1gUV7GGDlcOrZ7/FPYyo0RqQ=,iv:TtTektMjhWuMxPDcVBqi1w3gNYYw39pksuyMK27paXA=,tag:eCg13TTh85A6JJ8eSB3U7A==,type:str]
    redis-password: ENC[AES256_GCM,data:vu5y8salgH3VIQs+i8v8b3GcxXFfi2gMOZEJKg==,iv:68unkpvnkhKQzcdfaXhK8A+ZR7venZBztNJJWPiOH3o=,tag:tFalldvMDNPR/ruJKEC7ww==,type:str]
    DB_PASS: ENC[AES256_GCM,data:ey4TxLtVGmZps0H2Hljc5o5j9k16us1u9u1cxyB7v58=,iv:knign5ztPXej0j68R1FQb4f7lQCVh6zUb2dYMIZXXEk=,tag:lvtuO42b+G6QQ2LDAVZEWw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:80oVYLa2iUJu2BYi4tbyIRAHWnef7kw64An2nw==,iv:ocRPxA5mHpfkkhvOOErjeaQpfTMVenwHa3PywL6hyxk=,tag:+qAehXGVdSqWopEQN5lZ1w==,type:str]
    MASTODON_ADMIN_PASSWORD: ENC[AES256_GCM,data:iem0hkBqTISpkMpn,iv:rjOdtUdVi1+GYlye40op2ZSp8WkbKM30eJEu2dUFPEQ=,tag:tSmXEsL3xiTwdwWLvtQ8RA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:57H9J8XshV9NNfIr49szzH6Hygg=,iv:mFauMWU+n3gUsTayRpO1waLbMnqPU459Y671PgHtVrI=,tag:Jc56/S16wkUFsaShZwEVMg==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:xxRn4BkZnHo1axPta8K5Fq2yxbVmIg/D,iv:z3YuX550sB+tnDiphDVllUB9L9OwIiKMsWTsNgN/4SY=,tag:vMC0c7C988FQVLoHUSstgQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:pWarHA53wmOGawGobDJRSbd8jkZe6c35Np0+QxJ8Qc4UDuv5jrhG0OGgamF05W6eBuCt0M0KgDG0DnAm,iv:xyDlIu95L1QH4BdReCYPbr2xye7H604HeJ0K/9LZpUI=,tag:ynSGn3OQbYYtPXJhlQsIyQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:eDdPSaQ8U958dJ0s5JHC0ImnhiNXWBnEfTHfqLUR1WrfNeBzr/YYDDQ3apW8b7vWOvhqzpzSO3KxjavIb8YDA9SFWXKSGUKFztCcYDyn7C7gfT7YJ2Zceu+NF3v6hQG0JvXiGaMmhbZX8r9Sh2rlnHjvOfI=,iv:yzfJtE4kG1DxTI6+bplpnE2xrQMYa9Tjswy6xcfeLMI=,tag:mImXbZ4gNqwp0fjfKnOxhQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mastodon-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bCs4QThvS1N1UFlSWmpp
            UStxc1pNeU5ETmlIZ1l2Yy9xRkdoSlJmWmpRCkJJd3Jpb0Q4ZFVjblBuMzRNNHJP
            ckMrSnJBRE92UTgreFVmRHB5b3NhTlUKLS0tIEoxM2hNVEd1TDJGajhva3EyV05s
            eEhOdmhJMFJlbW4zRnJwbUVDdHErYmcKH1yCdGdtSqerlYQN8NCNHSHyph+Mehww
            IcIoRV4dMx+r3i2DZ43qsUnodb+u/GNQeU8UjskWANgQAUEcK2bTuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T15:08:28Z"
    mac: ENC[AES256_GCM,data:b/W7d9DfPHIN/yLtJxgpQ/lrCLr7Stz5fsVYuh6XfcW6LdbI8w7JPahiNPEEJ6xOqYrcf1RODQhGj+aBxVVXa7clLLO6h6Fd7dxzVduVf0uH2+STI7xHONUiCurwvrWeJ79dP/rCq/bm+iEnTEA0HFoIXdYFNQzedejFyQ6zw84=,iv:68RSoryM544cr02Y4g5rGxv50uNz/6FWoae5uRrccXY=,tag:KbINY+7XVLolEpicJ2c4Mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
