---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: upsnap
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: seriousm4x/upsnap
              tag: 5.1.4
            env:
              TZ: "${TIMEZONE}"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
    defaultPodOptions:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    service:
      main:
        controller: main
        ports:
          http:
            port: 8090
    persistence:
      main-config:
        existingClaim: upsnap-data
        globalMounts:
          - path: /app/pb_data 