---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upsnap-data
  namespace: home 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-backup 