---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pelican-data-pvc.yaml
- pelican-db-pvc.yaml
- mariadb-helm-release.yaml
- redis-helm-release.yaml
- panel-helm-release.yaml
- pelican-secrets.sops.yaml
- ingress.yaml
