---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pelican-mariadb
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: mariadb
              tag: "10.11"
            args:
              - --default-authentication-plugin=mysql_native_password
            env:
              MYSQL_DATABASE: panel
              MYSQL_USER: pelican
              MYSQL_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pelican-secrets
                    key: DB_ROOT_PASSWORD
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pelican-secrets
                    key: DB_PASSWORD
    service:
      main:
        controller: main
        ports:
          mysql:
            port: 3306
            protocol: TCP
    persistence:
      data:
        existingClaim: pelican-db
        globalMounts:
          - path: /var/lib/mysql
