---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-db
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
