apiVersion: v1
kind: Secret
metadata:
    name: pelican-secrets
    namespace: games
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:FxTgqRB3ZxuNvGczk2P/DNN4HpVwCTr/6vMDbSdsaUfFrd6++CZKHE/jVszGKAmzhP21,iv:nYINvS/Z50XgG8nyqz8egEB9evZxfTIVKPflDYVK8Sw=,tag:Iq8zkSibbiklxop7PO4QBA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:LFyYXe46YgaaKBWf/Eabr0ZTKyqEPWHU,iv:CyLK6jHkrQpdwsZC/xKXTzw2ZXav85XSSXe4fbKNhmM=,tag:rjyblFxko6ziGKWf4cp7yw==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:90O9xLxOrHj+XJ19LxcNR1vVha4OUTeT,iv:h4vIq43lo47jpYdyVn407LB4Uw3SSVqjwT+Wkw9FVlE=,tag:e3ttYSZQ99ogZNLsYgelWg==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk0xeFZpS3I1S3B0MFgx
            cnFBREVETHFEVjZSc0QvU1cwMjRHRHRadHhBCnNscXFEaEsxemg4T01LaXYxSElW
            d3dqaU5OR1lRdThRbTB3ZUVGaERhaEEKLS0tIHNQWVhUd3hPcWN4MmhUUnl6dEZi
            Y0dCSDJ0S01ielR5OFlzeGh3aHBDdkkKPoN5uDZwpcdZpXVpdCK699jZp1uOZjUu
            KQcD7n0lK8GKkzHrxHgGVVD83Ra2zbovWof7fOPW9dYTA+9CZ2Ikjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T05:52:43Z"
    mac: ENC[AES256_GCM,data:2WYDXxislmJCjfL4KClwv3/GZuQ+a14opkcroLtnm2TAivUnGel9fVY/4o1jz6DZe7aYSPSA70Z/1YFNS407em3A6p4KqBiNk6XiHaNZQ/yz+bhrdg3eqmdktQmahUNVlmXUsR4X4oVXxOBVbIYMif0GLxDK2sBoWucqWongZo8=,iv:2y3MduXwmhBNN7ACtMSx3bH+dMu+6KThmqhqsUiCjTo=,tag:MXfryj/l1dG5qPtDEkH4pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
