---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  path: ./apps/traefik/app
  targetNamespace: network
  interval: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system