---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 8gears-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://8gears.container-registry.com/chartrepo/library
  timeout: 2m
