apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts
  timeout: 2m