---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mastodon-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://raw.githubusercontent.com/mastodon/chart/main/chart
  timeout: 2m
