---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-server
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: haveagitgat/tdarr
              tag: 2.14.02
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8265
      server:
        enabled: true
        type: LoadBalancer
        controller: main
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/allow-shared-ip: external-svc
        ports:
          http:
            enabled: true
            port: 8266
    persistence:
      data:
        existingClaim: tdarr-data
        mountPath: /app/server
      media:
        existingClaim: data-nfs
        mountPath: /media
    ingress:
      main:
        enabled: true
        hosts:
          - host: "tdarr.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ak-outpost-media
                  port: 9000
