---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fireshare
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: plaxt-secrets
    image:
      repository: shaneisrael/fireshare
      tag: v1.2.14
    service:
      main:
        ports:
          http:
            enabled: true
            port: 80
    persistence:
      clips:
        enabled: true
        type: pvc
        existingClaim: data-nfs
        subPath:
          - path: Clips
            mountPath: /videos
      data:
        enabled: true
        type: pvc
        existingClaim: fireshare-data
        subPath:
          - path: data
            mountPath: /data
          - path: proccessed
            mountPath: /proccessed
