apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-zomboid-server-data-pvc
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
