---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.32.8.7639-fb6452ebf
            securityContext:
              runAsUser: 0
            resources:
              limits:
                gpu.intel.com/i915: "1"
    service:
      main:
        type: LoadBalancer
        controller: main
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LOCAL_LB_IP_INTEL}"
          metallb.universe.tf/allow-shared-ip: intel
        ports:
          http:
            port: 32400
            protocol: TCP
    persistence:
      main-config:
        existingClaim: plex-config
        globalMounts:
          - path: /config
      data:
        existingClaim: data-nfs
        globalMounts:
          - path: /sortedNFS
