---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mastodon
  namespace: flux-system
spec:
  path: ./apps/social/mastodon/app
  targetNamespace: social 
  interval: 10m
  prune: true
  dependsOn:
    - name: cnpg-cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mastodon
      namespace: social 
    - apiVersion: apps/v1
      kind: Deployment
      name: mastodon-web
      namespace: social