---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pangolin-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

