---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tdarr-server
  namespace: flux-system
spec:
  path: ./apps/tdarr/app-server
  targetNamespace: media
  interval: 10m
  prune: true
  dependsOn:
    - name: longhorn-app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tdarr-server
      namespace: media
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tdarr-node
  namespace: flux-system
spec:
  path: ./apps/tdarr/app-node
  targetNamespace: media
  interval: 10m
  prune: true
  dependsOn:
    - name: tdarr-server
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
