apiVersion: v1
data:
    GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:KrnBdcSgn2PkKZ7bKpNrb6BSqOa7NJDVHO7LwGofLVc=,iv:B8Jhti9hZwb36UDI3RJETxlYWFFrkJEFUX0VydfOPDY=,tag:K3v+t4gy4YB+TRLlcM7v0A==,type:str]
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:6mWdCa2NNCA=,iv:szydGX8CiNWKhPkDN+SpXmRjo5aAGQeeur9YsX6RMRU=,tag:6cjUxB5W68LzBlFHOPZW2A==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:T33p6zI+2gcaTq74,iv:M7Fo4ASz8jSiGvHWss2z0T+Jq4HGNoTRPDALvyJbk+M=,tag:kXan32pKBQs7lzjElRz59g==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:gfhU6Sc+iU2E9ekTgQtk7vyp3XZSk5dOsQuvre1hKviMg7nCWB0LycFWdfzXmUD8QlFPMd624hU=,iv:k/8+55mdCHHKbfKwtTvtAIfRtHFSeeQdO9RRc/jdbKs=,tag:q6iJy+bO5zMpf9Lt4t8C8A==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:m+C6NBW+yyR3AblgP7TaD+75f3lPkE3QzWPAUkFSGQntXexk0G8XUibBMy8s9sFR2rTA8USW1XOZi5d8DAUkP1TY5z61vl5p88D9zBe8XfD1oLHiMvpsJuo/9R2cFi+AKBcvTRpx1X9eixNx+Is2+9+66lA1pEeFFT9gAg32XlW6J5yazkkqgudej5lcxHnYIKYL0COKtKw3zecJLreLvtnioaUQqVeQNv0wDQ==,iv:CX0aKvCRQIeEDhdubvdhaqksFnGkaDoAI03OOGf+lnQ=,tag:Wvaj2ngRj7xW6KTkZNLEng==,type:str]
    GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:DZWaPK3MsObmYRRj5ARzUSqGfQ11Ni1bm8Bk9w==,iv:Wz6BQw3KXkzk/1L9t9WYWcZC6NafgUwY9Ip9yB07Cms=,tag:JBoil9Y9gCSK2lWrqWefiw==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:c093KRPAnYGh7CtTtrgtxK08OJrAkfKYSTJHFwBbSpK5RJrA8sOJBAUiMgn5lHwomT0+eLVyFMTf2Muk,iv:jzxkiHWB0nJ496K/xhFms2EPTcgbWOGkpqn77bzqY0Q=,tag:Sm+Gg0PumBtWhak2fqmlrQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:JVcUUNKZs1ra6MK98BwGUlMa37ZIjoCcArbdZsiVnTSOO8AR4rkwNp/VzFAMsyg8PDMuA76Ln4o=,iv:gfn+cacx4E+soSNeUxS7/p8SC08w/18aSKxrTGQYD1M=,tag:/IXgcCnM0Q9kqqJeM80+SA==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:ul2wpBVXMjm9v7wxHmFrhF6lu9x09s3EfclQ2vJvVewG6DtcxdmD17mcLb8mgPmKJdgYYhnPEOklc/uW,iv:f+tSx9C6rvGlzyTjBCmkkfglkSqRq4RGE4BULn6LvOI=,tag:ky8QJx6iqG/f2GMLAyQzjw==,type:str]
    GF_AUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:eMF3rgChAVkrdtvVE9v/4To/Tq3EbYf1RSr0/FHiF3j/fLE+Zh5zfZX1k1LSBU8MSR0R0SX/fSlmluTjfbmu1vPsSNdrLoND,iv:lUpgGB1Cm3TEiHsB2FrQMj2D0BFIIMs6vfv8x84ikNs=,tag:H7UXtsuFyDRlnD6Q+BBMzQ==,type:str]
    GF_AUTH_OAUTH_AUTO_LOGIN: ENC[AES256_GCM,data:BrLJFGC3H7A=,iv:2ENXV1+FgMQXlLdemoqB4O4X0CgPiE0n3wDUvDISAe0=,tag:kEdLhsEi6naY3EZwiqj0xA==,type:str]
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:F8/05dVjxZOoLJe+Z47Tw9peM64STTJSzBuuoRQ8QfHOGutyZKnuT9jpIvR5OFB44mqT1F0/saWtogz0JrIWRafnNIQ2D/3n4/CdgpClfurtzD8XtTSxXHsm2hsJaXOR+yilTGHWv1nXaW1jVLUHQc12FttTET3Q5jYUi9SkmC3CTnFBsRpE/kMcazJ9RulIZNUA+wnkktk=,iv:Wy3xIu6MolKxy0U/3LaJcGVseexRIckpwt7cHFMaU1o=,tag:/ga7xBgaUvbnbgJbwEeNUA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cmE2VkZzclFZWjNESjhY
            WE9iZzJoU2FUelBGV3BQb1RwNEhhU2FYWWs0Ck9tSjR6Z0tSNTJKSFh5Q0RsOVR3
            T290RlQ3Q2F3eTN6ZmFiYUg0ZVpvT2cKLS0tIE8vWlJHWXY0Ry9FbURWQ3FZdzRR
            aXFodXJKYWFWWU5va1BHc0hMMnNuWjgKVedju3tHhKUE42nLSF017doFloabfg/j
            AklfDplPjlBbwjZiveUZZVS456H3lZf/6fIQwQlCEjkVQMprlWr/BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T12:16:18Z"
    mac: ENC[AES256_GCM,data:gnA8JAMQFdny7Rp7590FaDe/vApirYty1r1jBZ4A2Dc1ieVvQ+8l+F/g259mna3HPJ+cv3Sb7JpdZ6IVuZCThBEolEo2abPpJeSLRpo1T5WNYwx25T9xUphxWCfw9PnAO80hbBrv3gnO/Xd4n+gDVeXGmLyanr6eJOTG8ka1xlg=,iv:sPunnovU+Xz2fpHsgqJIYp++ILIUM8KIEbclwOZ/MFw=,tag:mkleXtawphO2jHamwudCNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 4.0.0
