apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 0
        containers:
          main:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.24.1
            envFrom:
              - secretRef:
                  name: hoarder-secrets
      meili:
        containers:
          main:
            image:
              repository: getmeili/meilisearch
              tag: v1.14.0
            envFrom:
              - secretRef:
                  name: hoarder-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
      meili:
        controller: meili
        ports:
          http:
            port: 7700
    persistence:
      hoarder-data:
        existingClaim: hoarder-data
        advancedMounts:
          main: 
            main:
              - path: /data
      meili-data:
        existingClaim: meili-data
        advancedMounts:
          meili: 
            main:
              - path: /meili_data