---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-gpu-plugin 
  namespace: flux-system
spec:
  path: ./apps/intel-gpu-plugin/app
  targetNamespace: media
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: intel-device-plugins-gpu
      namespace: media
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: intel-device-plugins-operator
      namespace: media
