apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/tautulli
              tag: 2.13.2
    service:
      main:
        ports:
          http:
            port: 8181 
    persistence:
      main-config:
        existingClaim: tautulli-config
        globalMounts:
          - mountPath: /config
    ingress:
      main:
        enabled: true
        hosts:
          - host: "tautulli.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 8181
