---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/tautulli
      tag: 2.12.4
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8181 
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config
        mountPath: /config
    ingress:
      main:
        enabled: true
        hosts:
          - host: "tautulli.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: tautulli
                  port: 8181
