apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:1xOBnCbHzWKzf1KMNOJUuLGeaFyBFEUJ0nt3NmlMCvXBd6cC0PNDIvUF+Do=,iv:DZQr438o70enZbcVWxWej5VaOdqPKH3Bq2AJ+nKkLHY=,tag:KaWgnthwOlKPFsp+eZ6gHQ==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:dOiKLA4cfZo4BjY2daNPqSLeCDRN1sn3SCg+DSGjM+xyw3n13YmuK2ALv2CrptXqT8apoF+UaJBffkjJTOXv8wwjaSuJODQxb7qDMw7VecmHKtgNlF1P2Dki8X/nNSUlagexIQ9No2+FcUjNRWFGnxz5VW4RRGN8EVOwMMOPV8ZlBeQty0oPLy4GpTZZWkUg,iv:lHSiFHXBfZJzeYWDItdbIzQJLKVsD/pTk3m1U3uS5vI=,tag:HKNyEb0Gyn7t2nnNste6OQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:GYB8k/t3Vt9Zw5ZaNDlNWwuyZfK3yI6KgE7EZlo+ASEbzszSvqkKhd/rmI8fxgk6e8QsG6fkTcSdDlYxg9KQllVcdUqJKKu6epbVdE9luDFCKcrtF1jKH8mqIU+Ud5Nir2r8ZFDDR8/+jW81j7WEqGrHytSdNYOu4xlYy3hMBr0qR7wF9ATHWYNKGoWO68PyOFs76fGK8xT+7kff5tHl7FVI2RrPJ6xPp6EBEbLJqgMhM/Wn2hkjT45hUQlhKcD5l/D2af2iWt02dM4fmDqELGaNU4rnxpovUmPKig==,iv:fK4vRowdAUlqaef2+Y9trBzsMRQLXpGoyQSiQ+ZjNPU=,tag:fsgrldDdsq8vyY5qHvUsGA==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4anJMSm55bk0xRGlaNU5t
            bk5aQldyK0MvVStMeFFCSWJ1UHlwU3lsY0hBClJySFR6RXIzd05ZNEdjVzdycWxW
            M1Y3M2d3NHNmMncydHoyVEF5aGdUdWsKLS0tIGNqWUx2UHRiSGl1bVNmQjJWeTRt
            ZStZUkkvRWEvRjFTVy9aU2JBeGNQZkkKXnc16bsJNO8fcuau6ZqlO8af7ZlOERJ+
            EUPUxEWBtffIBZXKwFL3uYd+UQqy0zpuYATBszFuSsUotUu0UbRZvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:12:04Z"
    mac: ENC[AES256_GCM,data:hUgxmrSrcFh+V+FIIVEhznlQ5r9QADl/AyEeVc0x4QhTrAIkBCKPqL7RDmxWJjAgK/y7gzceAi+FeJteFHTHZIzU5opfjeBj5+PW30s0P8PDI3LvEhkilfE/Hi8CnEmiBfdSmvfCn6BnQGOLTxeuqZChvLZWPQCFm4plNBZJHa8=,iv:3EeyOofG05xsOHsE+jeA/nDhthC3BC+mAFuWTbRWTlY=,tag:OSOoCRuC+1kDXuY47yinDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
