apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:zzqXf45UGezBPQ15tmS+7SI/uMWFq/IVVb+bUQdFaXXIewaIJM0h9En6JEs=,iv:DiIVLtvv2tHhmP4cC6D55FhtMs3PizUKmrIXmx/xX+E=,tag:gGULEnoZKj4yGSNu8kc+aw==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8sQ0aPc8KQ+3ra9bVVLhwRy+NiLDf4FU4EwEUKoy1GVX9hRCAXDwiVXRvqaiFBeGuqw5HMwPmYYRWKuyk6KPDWvhFmN9yO+Xnd8TUzeXUXHs2KgLfVRjzv64QX/gA1VYZlsKkB2mhol35ylKBS4BttWA385tMGK5Gko/gFORsnKm4zQ1SYLZZC5r9kXyHW7x,iv:Ub2gXlRPs5tDCwph8GZtVtt9FNn+h+/Y5s6CnLTr9aA=,tag:nOk0+EL5k59e+twkK06/Hw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:WycRfV0S2g9Vw/vMihQqAwf/VP5n83ZFQlIglHkbdWJk8V+fhoDRfXL0o8debeuXYK07TumxVVjgHK9VJiBV4YFTazV9FrXBeN5Kwug0hGo8sKlTG71tXnfi+0GRHZEjE0V6rBFXyyt7mjM9VlfyxpdtSZNFSHyDNboZHPWLxkC1AP9aoABW8UAycW9vm5enORQSpHtaIqrFhwy8UfUjzquxsf9MUBuQP5GVItvajs+mWpErCc5adQ5gmTURWirLsPGwNtcLTnbi3F85zLOGMXtpQoZd0M/CdjxfgA==,iv:/MXAFuuxxrX+eyGoAE+qCEanVVRFD6Qa91BImRm/Ba8=,tag:QHKR3Hd8NH1Pi8wElxRjuQ==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzhibWRuQ2dTdTFia2Uv
            N0Z4Y2g4ZkJ6T1BKeDRlUVJXdThYVTVjOFY0CldIWFJ4WFpZMlZ4TDN5eGdHdXpt
            QTVTYUpORUVxUGtmbE1SNU1iRGNaY0UKLS0tIGxSR1daZGU4TGhXOCt3WTBOV2po
            enVMbjVWOURPTnI0MXpjelpWYzJWRUkKfQLZw60mrh/wGGM3RmknbaFJXaWYh/JM
            vjGm1abEwul0uLkJu+wWxmDlNC1ljZNqN82uoGAI8DDz0suhh57V6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:09:19Z"
    mac: ENC[AES256_GCM,data:JV47WpdqkRJfaWrE48amkDQsaz7u+dW0BxO/qxBnLfiEYoyXnAV7wlIw5d8lYHbTGpBLB69TceJEWVmzwoGqeSMRVwXgtzWezznrmY2kv3RE+tXyPIVtvlRzWjPcL/hz92mO+uw9plCqFTQQteIeH+GGpj393l+ridgPh3JQRis=,iv:SY5SpUG9qHTMkZyRiXHdEgS1XYs6v8Z4o3jKzrN1Jsk=,tag:HL5MYqTlBsm+lYDPRbmKDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
