apiVersion: v1
data:
    ZONE_ID: ENC[AES256_GCM,data:BshBrKtNB7ts8XWe3XC3tLOpCDf7hNl14nMOzSPR3u3XiUwMgubthc+Bwac=,iv:eL4TEMjCpN60SjI0a5zuCfoggu8Tm9c4JCX+IeujSMs=,tag:7fpGH2eB/ZT7ueFemPPEtw==,type:str]
    RECORD_ID: ENC[AES256_GCM,data:F+FialbfqoPkcf23Kd7trnYjxsjyWytl/71ACsalV13LyfGmudcxTLk52rY=,iv:BVhrSRQZq4u5f5eKWso/17P1y69VHXjO33mzefV14gI=,tag:crdLKQyYx30t3goGtEx0Fg==,type:str]
    AUTH_KEY: ENC[AES256_GCM,data:xWJrf0EMPjHxzzFv1x7Q5MWutkvJepwXVUYXSU28MLRVz3SHYa9fKSTOa8AiGQp6GgWvDg==,iv:l36quxs+o+MHC9Xi4+L05yXElEWyEe5tf6n19KCunns=,tag:IitQOtmZfArTxTjySLoubw==,type:str]
    AUTH_EMAIL: ENC[AES256_GCM,data:Y+oHU3kEUE30G0EyIeHoAcJRp8E=,iv:vqcChcYnnEBrmPLpgS//vb6G4LAkzIfqgkh9aQpl+pE=,tag:BuMtyGubulpQqzxXyyeC+g==,type:str]
    NAME: ENC[AES256_GCM,data:dC3Rm03EDdgJeJV+,iv:c9Ef7IuA6KXFDzI6DKTaWBdODjztT7cq1j/ewSsSYQk=,tag:FPt4VYa0UFvGfKXXB3BjGw==,type:str]
    PROXIED: ENC[AES256_GCM,data:P/5mZI5LV+E=,iv:6nhYyXQT1v75Lk2Wknbdd7PYRvHVYN9/p/aAb+ulcng=,tag:D7rTj1ULpX30hyNGKVECLQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cf-ddns-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdjgvRVNZYWIwaEpvNDVO
            WGRLb2FNSkJsWDAzeUxYVHp4aGpKMWp3K1hzCkJVRURGNTl2RG0wT2IrdHB6SXJi
            RllkN1N2S3RldjNYVWVOYyttNnBQY0UKLS0tIHI1RkUrTUtzOEhTR1JLMldVcHg2
            NXB6c2F6cTIrK1l5d0hUdmtMZVdDVnMKyFPz+wuFor9vD1rR/bNjrZIIajT7eosB
            /AJhGy+q19mmt8vBz2Q3B/EXc0OBtXky8AFsqNXqq/lzsR5YDxXrtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T08:15:24Z"
    mac: ENC[AES256_GCM,data:QNL/YRXI0kzHbUQrqRlZy8aJQl/7dGaRq9REYdSR6oVuRaOqOT+VDswoy3lX8hltadtJzJiPS7g6MIYOLASNwXZubf54A6NZ4pQUZAvYI0BaqVz9bRgxtIggP+Pi3x5+aAeuVLMVWw5njiM6G8pR1M/hVrmZlAN7MvTINiX2lDU=,iv:5etSApwMX6erbOOxQRdCQe9P0SbH1U4iS8E4XkN0M8g=,tag:tAzUsOel91TFzUx+IL9d3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
