apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:latest
              envFrom:
                - secretRef:
                  name: cf-ddns-secrets
          restartPolicy: OnFailure