apiVersion: v1
data:
    ZONE_ID: OTgyYjIxMjk2MGVjZjA0MGFkODcwZjY5ZGM4NjE1MDE=
    RECORD_ID: YzMyNGUyYmZmYWE3MjQzOTU4NjBiNzUzM2IwMzUyYzA=
    AUTH_KEY: M2RmOTljZjNmYTg4OTNmNmY1ZTA3OTVlYmYwN2Y0YmNhMWRiNA==
    AUTH_EMAIL: ZGF2aWRAbGlhdy5tZQ==
    NAME: cmluZ3RhbGUuaW8=
    PROXIED: ZmFsc2U=
kind: Secret
metadata:
    creationTimestamp: null
    name: secondary-cf-ddns-secrets
