---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
spec:
  interval: 5m
  chart:
    spec:
      chart: mastodon
      version: 2.1.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    localDomain: "${PUBLIC_HOSTNAME}"
    webDomain: "mast.${PUBLIC_HOSTNAME}"
    existingSecret: mastodon-secrets
    extraConfigExistingSecret: mastodon-oidc-secrets
    smtp:
      server: smtp.sendgrid.net
      from_address: "admin@${PUBLIC_HOSTNAME}"
      tls: false
      existingSecret: mastodon-mail-secrets
    postgresql:
      enabled: false
    redis:
      existingSecret: mastodon-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
    minio:
      enabled: false
    externalS3:
      host: minio.data.svc.cluster.local
      port: 9000
      existingSecret: mastodon-secrets
      existingSecretAccessKeyIDKey: MINIO_ACCESS_KEY
      existingSecretKeySecretKey: MINIO_SECRET_KEY
      protocol: https
    externalDatabase:
      host: data-cluster-rw.data.svc.cluster.local
      port: 5432
      user: mastodon
      existingSecret: mastodon-secrets
      existingSecretPasswordKey: DB_PASS
      database: mastodon
    apache:
      enabled: false
    initJob:
      # annotations:
      createAdmin: false