apiVersion: v1
data:
    SMTP_LOGIN: ENC[AES256_GCM,data:uhHGxQjGnbw=,iv:xZ/ARp3SAvn3zL7VScAZ7a8A2aOAP68PrRhaQ8HyZ5U=,tag:ydJ7r5NAZcNYdH24kyYIQA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:sNmqhFeQ7GXWbIL0koBKtFxkDAXMsXKZULXLi09uJv1CHFCpXnVVA1xdlyvHWbVyI05PTLPXOZQseoAS1Tm5WqgE1UpiIE3C99dWz2CHMM1++fSR+8j/zCuQVFY=,iv:bkIRL3WFIOZmyz9X/VdbKDKiE2nhLHO5PEcoyzqjq/0=,tag:ATElSq5nAwEv5eO/ooV4Eg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mastodon-mail-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaXovNXVYWkQveVpwZUFD
            RjI5VkdJbjhXdk5Vemcxb2J1SjVyRCtpQ1ZnCjJwNUlTc3V1UGFBZUZzU0lDbU8r
            VHliVDR4WmkrRHVTYlNUZ2xkMHlNQUEKLS0tIEpERGk1USsyY0NtclAxQU5vRTh5
            bmh0d21CS0FmdHNZT3BSSmxtN3V3OW8KzIGSFuHYdPah45g4lr7GyJYeBFEyy409
            0Bo+JeBu8J52ik4PgGTNz/NebotxJ6ZJEayucV16LO0ExS9/DlTWQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-24T10:29:30Z"
    mac: ENC[AES256_GCM,data:P7i8SEebrpDAbd4raXWJLfZu/M86OtoL8+FMq7QAm+HKNjryLIw8xHCaLEGju6sFNU1soBQpyDYP5eKVg7YEIt0XBdavcmBIHkuHuQzzGnPC1JmLnXDHr9AEzxPG5Mqkp93m5+QyNoYUHl1yC2uIqqSQk0Bmg5ZfuFJe/TEw0uE=,iv:Hzg25GYH9xjFKQTcKHBpGoMCuSjrEhP5ToWfIUpFR9o=,tag:Se9THDRDt6B2KefMMyJUfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
