apiVersion: v1
data:
    DB_PASS: ENC[AES256_GCM,data:aSejc3WnAZ3/fT8AcOTYrggcIwQ=,iv:yxil1+1XbW6/YSWpUtqHltAQW+rcIytOl8aT1Bn8ByQ=,tag:mY2+ZzT0hXGg/YvA3iyiqg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:v7KCWfW9fa7T8kTmlk0Q6L8jMeBLmACFjgbTIw==,iv:D0f65RvWjIcxt2RqSWj7+9vR/9oJkTBcXyu8b3N7pUk=,tag:teuBZD5/KY9dO7I8qTeCVQ==,type:str]
    MASTODON_ADMIN_PASSWORD: ENC[AES256_GCM,data:iem0hkBqTISpkMpn,iv:rjOdtUdVi1+GYlye40op2ZSp8WkbKM30eJEu2dUFPEQ=,tag:tSmXEsL3xiTwdwWLvtQ8RA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:57H9J8XshV9NNfIr49szzH6Hygg=,iv:mFauMWU+n3gUsTayRpO1waLbMnqPU459Y671PgHtVrI=,tag:Jc56/S16wkUFsaShZwEVMg==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:xxRn4BkZnHo1axPta8K5Fq2yxbVmIg/D,iv:z3YuX550sB+tnDiphDVllUB9L9OwIiKMsWTsNgN/4SY=,tag:vMC0c7C988FQVLoHUSstgQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:pWarHA53wmOGawGobDJRSbd8jkZe6c35Np0+QxJ8Qc4UDuv5jrhG0OGgamF05W6eBuCt0M0KgDG0DnAm,iv:xyDlIu95L1QH4BdReCYPbr2xye7H604HeJ0K/9LZpUI=,tag:ynSGn3OQbYYtPXJhlQsIyQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:eDdPSaQ8U958dJ0s5JHC0ImnhiNXWBnEfTHfqLUR1WrfNeBzr/YYDDQ3apW8b7vWOvhqzpzSO3KxjavIb8YDA9SFWXKSGUKFztCcYDyn7C7gfT7YJ2Zceu+NF3v6hQG0JvXiGaMmhbZX8r9Sh2rlnHjvOfI=,iv:yzfJtE4kG1DxTI6+bplpnE2xrQMYa9Tjswy6xcfeLMI=,tag:mImXbZ4gNqwp0fjfKnOxhQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:GPrjzf4pkEZdyRjvtGMp0FrDj/SYTpIACqA3qg==,iv:+31ZHFpK5Z+zW7LYCksbClPXflA7SuD0jEPp2QcJfQw=,tag:flrsDPaqmw1gz/k0b/OZMg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:6RPX6AwCSnwgMPxALL/JmlCP9Po05dSweWVO8277vzVPzW3gFMWnpCCl6SJfv7o33RamltOfJpM=,iv:NtCSKWhr3ndzYhIiN9w8j9JIVrgTr7AYGZUPThMCDSw=,tag:nKgy9fhy/Gdd0i1uKUdrQg==,type:str]
    S3_OVERRIDE_PATH_STYLE: ENC[AES256_GCM,data:fyfNTI/Oljo=,iv:IMP8VvBabuIjRk15+NNFACU9Lvq3UvTY+Ns+HF74aZQ=,tag:MbMGcxyQIhOX16gwPqzC4w==,type:str]
    S3_ALIAS_HOST: ENC[AES256_GCM,data:XAKr208SzUarZzC/9N6Vyy7djUQfo0WvMl9ImNrHOeU=,iv:8SZKb/reolWlsKF8jG5B/FnFU5LKt/88UXXY60VS+8Y=,tag:2J7gV1Nw4eNqxHZ9VIthCg==,type:str]
    STREAMING_API_BASE_URL: ENC[AES256_GCM,data:tOUwCa9SK9CQFMNVSPiVotsRgE5E8sIthrPdG+ZnD81qyZcm1Jp0Mg==,iv:AOvrdmQ0A0CexcPL2SfRiaip/ipeQQWw3st1mtFf4ss=,tag:hvxG04PohOhYvMJDvsNR5A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mastodon-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bCs4QThvS1N1UFlSWmpp
            UStxc1pNeU5ETmlIZ1l2Yy9xRkdoSlJmWmpRCkJJd3Jpb0Q4ZFVjblBuMzRNNHJP
            ckMrSnJBRE92UTgreFVmRHB5b3NhTlUKLS0tIEoxM2hNVEd1TDJGajhva3EyV05s
            eEhOdmhJMFJlbW4zRnJwbUVDdHErYmcKH1yCdGdtSqerlYQN8NCNHSHyph+Mehww
            IcIoRV4dMx+r3i2DZ43qsUnodb+u/GNQeU8UjskWANgQAUEcK2bTuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T08:09:09Z"
    mac: ENC[AES256_GCM,data:CfkOYDTbw9nUwvxqPmlsO91XIWYJbxsUA5I9YZVD9wRGWncPr0Pak7lOR4BQIZmJTcibY28fMDRmxnvr7mCg5Tbmr3383VAiEr4F/Cw6c8fiYcicyVJtAZyduRwTqOC2FWjlTs/TqkMrtoocXIdrCHblRKsQuIEyDAaiMZAYxCA=,iv:o+v5H56UouGKEARLpOdfBSn+SKb/hO5NsesojRXlg/A=,tag:W8/9fDJnSj9IfoVV16llmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
