apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr
              tag: 4.0.1
            securityContext:
              runAsUser: 0
    service:
      main:
        ports:
          http:
            port: 8989
    persistence:
      main-config:
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      data:
        existingClaim: data-nfs
        globalMounts:
          - path: /data
      downloads:
        existingClaim: media-download
        globalMounts:
          - path: /downloads
    ingress:
      main:
        enabled: true
        hosts:
          - host: "sonarr.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http