apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/sonarr
      tag: develop-version-4.0.0.421
    service:
      main:
        ports:
          http:
            enabled: true
            port: 8989
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
        mountPath: /config
      data:
        enabled: true
        existingClaim: data-nfs
        mountPath: /data
    ingress:
      main:
        enabled: true
        hosts:
          - host: "sonarr.${PUBLIC_HOSTNAME}"
            paths: 
            - path: /
              pathType: Prefix
              service:
                name: ak-outpost-media
                port: 9000

