---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: true-charts
        namespace: flux-system
  values:
    image:
      tag: 3.0.9.1549
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
        mountPath: /config
