---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 0
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.1
            securityContext:
              runAsUser: 568
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    persistence:
      main-config:
        existingClaim: sabnzbd-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /downloads
            subPath: Downloads