apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    longhornConversionWebhook:
      replicas: 0
    longhornAdmissionWebhook:
      replicas: 0
    longhornRecoveryBackend:
      replicas: 0
    defaultSettings:
      backupTarget: "s3://longhorn@us-east-1/"
      backupTargetCredentialSecret: longhorn-backup-secret
      defaultLonghornStaticStorageClass: longhorn-backup
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
