apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ruVOq648M9NfwHG3ZmVepgiz4FNBOUf5K1Rm7xv+poaMNqkH,iv:bARzHJvjJrtVoEC7ikReyLQc54sSyemt7VTkvwhFNQQ=,tag:Bq9cjmhBufLzJpx8sH4SYw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sf5w60ZmaUbXcyyzVvyiOcBbZAa2q/vJoExhy7Y6sOQk61S+ETAR9ZZsXmk=,iv:STwKkGEOxbAwWnMHx8YS5sXg39cZ91n0ZBpSF3wsntg=,tag:ypdN33H2wbssuUaAHqJsgg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:oz194h/TLmpVFkoP6p8SbJ0V9febVhFhyG5EEVye7CHXOudu6vqjag==,iv:/iDLC/edbFY1tOCw2xrbzQc5xws5qa1h4gDk+P0x/+Y=,tag:KTJuozJi9845UO6nuPMgZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: longhorn-backup-secret
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS1orWm1wY0VYSmdVVHRS
            N3NxT2NrTXJCUjZ3WXIyTW1YVHFpYU9MWUFRCmpxb0hFNnJUYkNEN3pvNFg1dkdY
            VUhaQzlWSE5QNjFsYTc2dmQ3MjVtNTQKLS0tIHIyeWFNQllhSHI4Y0hCcHpybXB5
            eVpvbWZJNVRXdVJIK1pQdXpQYkNzdHMK5P//kFo0noo/yTGjNBg/kWwmn5vK221N
            5ggs8HTimmrZ4iQHTmhEW0v9D/Uolcsgf52Rdk1axl1rt+yQjltWIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T02:11:41Z"
    mac: ENC[AES256_GCM,data:XabbVF4J66E4cOjWdbX5TWnAtWe86SLYcdSf54ya/hwuzTXImBOw3z3qAKCmRIeKSXCvWEhoyHYI+qg1VMHKOyfrOsUK8Vm9/8ykUZTBKLvFzxlldVEkgA31p3/jcnPuTLODEm3zSFfQ/UvSF8EJCT4mDDbpbnmfrRtLjNfsGiQ=,iv:hiv9Cq/Zba7Vhf+/88cBwITZBwIizZ78z+Sp4um+VkU=,tag:Jpao6ggNzwoXfdAru3UDQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 4.0.0
