apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vsWW8d3ud7xouI9aQdZ+mGNGsu0QdDbyvBv7LNQL+OCqRuUZYJQWJg==,iv:J3+gr6P6mlODQuEVuY+S8wc0kTpIWWDExbY2m4V+gqw=,tag:DYjUS8gRNnkf1x5/ClcO/Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0wjD6k6Z06FtZt5kyfNjCFyLRGfsXcxA3/XHguHQhhy738occwqDNc/oRccKAPV5S+mpGRJ+YKAeqxDEeN3h7GcDV3bgX3tc,iv:MYIvCzx/J0NbNuu3Ic2Ue3rvZTjoOVno6I16EgtcP2s=,tag:Nubl1KkH9vBpF9IGWYHKPQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:lNloreMFF1E8rL/D4ValZbjam8TkLI6BZp8noDhVuf8BcljwxqUOWQ==,iv:VuiNlyG1OHpFj5r3SkQACtiiSdFjJeDNuyuI+Nw2ipI=,tag:i5Y70KY8EEPFcAf7ZqiHGA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: longhorn-backup-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS1orWm1wY0VYSmdVVHRS
            N3NxT2NrTXJCUjZ3WXIyTW1YVHFpYU9MWUFRCmpxb0hFNnJUYkNEN3pvNFg1dkdY
            VUhaQzlWSE5QNjFsYTc2dmQ3MjVtNTQKLS0tIHIyeWFNQllhSHI4Y0hCcHpybXB5
            eVpvbWZJNVRXdVJIK1pQdXpQYkNzdHMK5P//kFo0noo/yTGjNBg/kWwmn5vK221N
            5ggs8HTimmrZ4iQHTmhEW0v9D/Uolcsgf52Rdk1axl1rt+yQjltWIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T04:08:51Z"
    mac: ENC[AES256_GCM,data:dOBcewFxvVPb76nRcxnv8dulQ2gGyZZaYe8MuKOxUhqj7ytipJXYHHmgngHSPZoBVx4vYu9B36FNH/7S7e8kldwyAiA526HIxjZ0uk95aSQWgfYoBMbVtbKULQd3VyG+VZnJC/hjH/wUWAGohsJWbNAJuKjWkCEftXprsgYkOIM=,iv:ahi5FEcKOmS85eMzNso8Ca0WZLRf5WnKVhHr7O+OnO4=,tag:gPRMxEe6LqOigg6htMyH/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 4.0.0
