kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: "ext4"
  recurringJobSelector: '[ { "name":"snapshot-daily", "isGroup":false }, { "name":"backup-weekly", "isGroup":false } ]'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-xfs
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: "xfs"
