apiVersion: v1
kind: Secret
metadata:
    name: paperclip-pg-cnpg-secrets
data:
    username: ENC[AES256_GCM,data:fKdXKBFk4JE9n3nG,iv:yfvSesdlHBg+WF+TD+jXfbw68VhMoi6YVvx9xbOp1jY=,tag:JMkBIZQ/Mbx5U/mkIavFow==,type:str]
    password: ENC[AES256_GCM,data:/qLsu53NmtaFbdWmrzADAp0r3nF3O45Z,iv:emETP9Mw8YfRkDoejssb1RAdJP9rtx4u5jSKg/8ouns=,tag:msnsiXp9+sT5SOd1brdlaA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:0DaLic70p18jW6UAq7HPcVUUblmmLraxmaJD77q20pApYEI+qZCGQw==,iv:nK0BvftRFL9dD1C0IEIvDq5TgYPxHC649dKvESyTfbw=,tag:MDmcXEXyuCvY+JIZa8m3CQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:gmgP3ED15uFre4xS6GJaVouFb6fBYcD9KWiJOh59GSBVpjN1Rx0Ofjn7HDwv4nDRQTo6LunBkgMozD9B/+FP7ZES9AoRMQKF,iv:z8AUzhOy0N0CjifdwymGEgv95uB9xnGKzj3U3SqNxoY=,tag:J5nWyYacggJJtwb4YMea2w==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRVBsZ2FmcU4xTnExWWlp
            V0tsb0plMDRJNHg3UDBLc0g0ZGR2Y1p1anlvCjFsMDl3VE5VVWtwdmtEMFkxSUln
            ZGxZc05DVkg2Sm1SMkhNc2VYNU9tdlEKLS0tIG52WkdDS3YrNzU2WWpkeG81cmw2
            RVIyUlZxQWZDeC9OZTBKU3RGZFhlVlEKkySB5+QPxBoDMwA3NmAr2oA0wPGkKsbA
            MkhYE6wC75N0Udoopx5KD12FeZs4zwN7YtALiw7tZLRd5NbKdnFbBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:08:19Z"
    mac: ENC[AES256_GCM,data:xWtsG8F2YRNebX1ab4TwmD5Miy9AaiJxsM5gdIWHfwRNgM1ixlfpAbb1eXYjddIWoTvPqOjvmik/KQqtpp6UyNITvzi2xi8WuN2RO6JyFyvKQexFEFcFr1fpQwzOFQb/k5hj3CUsUsDIIl0+bvhXROWa238GWLWjxO3stei5KtU=,iv:YQC9Wk0Jk3us7VIArYEmm50qnO0CbWvDDLl/x+3rTPk=,tag:cizBInBqajGr7z+TGbbd4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
