apiVersion: v1
kind: Secret
metadata:
    name: paperclip-pg-cnpg-secrets
data:
    username: ENC[AES256_GCM,data:RN+1YeY0Bst3ZKF2,iv:eXa0+ov2q5ftWkOjOO+EJmSB5oy8gQzJ0QxJx3EvfCs=,tag:hm/bDCqCRZFxd5e/jK4yXA==,type:str]
    password: ENC[AES256_GCM,data:gbaEg6tJsAr+bUSXjfYK0G+KECkLq84y,iv:hW+RUX0aK88We+7PHASxUpOAxDwCi2Rve79kQGQc4dM=,tag:rRM48U+0r0BS5Pbf+1GUYA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:CM3S3tzs08W9YY8RkT1xJ8VRKHj1K1Fpy+i3qZ8lVMov2fUsDEEGMw==,iv:Agpqch8lV5q9Cqks0QlXlS/sygXUIKe2PRgm5vWOVgs=,tag:9eBJx6L1kqm/HKhpn3PQ0g==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:om2xRp46Dz/WNwJGV6qRcrLyo6BX6NBaQfeuj3eaF1mGkIpmh6W/1KH5MiFXkEaomIQ/MyERebWAZ81ImLKN5AOZvd1bjx/t,iv:YBwBg+4xDvT8NszmomxbuQP+VQJXwF2VtifoXXsTw0s=,tag:8rIgUPuM6tI+3DS+aD1LNg==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVHc2Zk1aZTZGOVlCeWdq
            V055RE95Y1hwRUdvMnA2RlNKRGY3S0M1S1VNCkJ3WFp1WEFSclVNM0k4UXhnTEUw
            SDYwTGFUcWNQbzlFRVA5b29XbnZNREEKLS0tIDdicStMZExUN0ZEYkgzSi85RnRM
            bVVjUVJBNFh4VDN5V1hKY1NHR0pzZW8Kh+ley23P6VjF4RbxrmevgpC9tmHoaj9C
            TeucA+DOuLuWQN8dYJElfe+LcI0haLtZQ3pqgOr4QLnS1deM2kvREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:14:13Z"
    mac: ENC[AES256_GCM,data:Rt+hgk5XSG/aauocvZJw/zInvhjIxOgQhvEmk33CNmNGLttxsZ4QHG1AHExPhLqFX9zgOr7dUpnCdmSNQiG4pzRKHoXCKxk0pyp0G/cSgE0SU04IYKLP4E8KvmFa66HOGXllBEC3h/rdtQoJk1bldt7gCoU59ntYSCybuwzIHXY=,iv:3I/7p6eSGkANd5a6GaD3WIs86KFK8Xvs9O7dYs7NZBA=,tag:rTRDWUkUjq2Jf+n87Qa4NA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
