apiVersion: v1
kind: Secret
metadata:
    name: paperclip-pg-cnpg-secrets
data:
    username: ENC[AES256_GCM,data:fKdXKBFk4JE9n3nG,iv:yfvSesdlHBg+WF+TD+jXfbw68VhMoi6YVvx9xbOp1jY=,tag:JMkBIZQ/Mbx5U/mkIavFow==,type:str]
    password: ENC[AES256_GCM,data:/qLsu53NmtaFbdWmrzADAp0r3nF3O45Z,iv:emETP9Mw8YfRkDoejssb1RAdJP9rtx4u5jSKg/8ouns=,tag:msnsiXp9+sT5SOd1brdlaA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:094rqz8X3r1PdN42gb8q45G59nueGWxpMkVo17rdvedeJpWe,iv:MsHHxE+aAvLmJt/qZDmiKWt7/5GirfDspwoQ+szs6M0=,tag:KVK+vXWP4pUNDMLHpzSblA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:6ZxdTPBdW6P6PUpJ6i9jMM2Xl4ABJvJ/CgVcMnrXBvnkxiqGzdEMhg94wY0=,iv:XttcAtw2eVxOPFnlW2ses3/xfXAQGR+ChoYQS+1yNJE=,tag:HNXA1V+osokLZo/xcYpJLA==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRVBsZ2FmcU4xTnExWWlp
            V0tsb0plMDRJNHg3UDBLc0g0ZGR2Y1p1anlvCjFsMDl3VE5VVWtwdmtEMFkxSUln
            ZGxZc05DVkg2Sm1SMkhNc2VYNU9tdlEKLS0tIG52WkdDS3YrNzU2WWpkeG81cmw2
            RVIyUlZxQWZDeC9OZTBKU3RGZFhlVlEKkySB5+QPxBoDMwA3NmAr2oA0wPGkKsbA
            MkhYE6wC75N0Udoopx5KD12FeZs4zwN7YtALiw7tZLRd5NbKdnFbBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T00:16:46Z"
    mac: ENC[AES256_GCM,data:PCdA8RzeuYtyojVkjCnv5coE6FtPr+P9X5UDphiV0Kc/d4J93dgfb71Ruo5Vi3fn/sFgY/7wM+M14n9b+AN9FG+MxvM4Lc5bLLu5IXWV/v1sFevUwvLlq4taZBjwsCCXUBi6l8EthSxHmJSHdVxdgwsK/sGbL0kWOi3WeAb59Xo=,iv:1vRu4YI8t7ZwHZs4GbFQODEuNCj7KiA9E2vyJ844nn0=,tag:12I9ZL4ysPQ5oL/E6ijTTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
