---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoview
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
    envFrom:
      - secretRef:
          name: photoview-secrets
    env:
      PHOTOVIEW_DATABASE_DRIVER: postgres
      PHOTOVIEW_MEDIA_CACHE: /app/cache
    image:
      repository: viktorstrate/photoview
      tag: linux-amd64-30c1b2a1-push
    service:
      main:
        ports:
          http:
            enabled: true
            port: 80
    persistence:
      photos:
        enabled: true
        type: pvc
        existingClaim: photos-nfs
        mountPath: /photos
      cache:
        enabled: true
        type: pvc
        existingClaim: photoview-cache
        mountPath: /app/cache
        subPath:
          - path: cache
            mountPath: /app/cache
