---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sons-of-the-forest-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
