---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost-ringtale
  namespace: flux-system
spec:
  path: ./apps/public/ghost-ringtale/app
  targetNamespace: public
  interval: 10m
  prune: true
  dependsOn:
    - name: longhorn-app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ghost-ringtale
      namespace: public
