---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
