---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16-alpine
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: 3001
    persistence:
      main-config:
        existingClaim: uptime-kuma-config
        globalMounts:
          - path: /app/data