---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static
spec:
  config: '{
      "name": "macvlan-static",
      "type": "macvlan",
      "master": "eth0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/27",
        "rangeStart": "192.168.1.170",
        "rangeEnd": "192.168.1.180"
      }
    }'