apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: "2.1.5"
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  values:
    reloader:
      watchGlobally: true
      enableHA: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi 