---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-app
  namespace: flux-system
spec:
  path: ./apps/games/minecraft/app
  targetNamespace: games
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minecraft 
      namespace: games
