apiVersion: v1
kind: Secret
metadata:
    name: postiz-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:tQ15SLToO10vChJHK8G1lzLORopn55DHePN4prnCdUAa/GCuEnCcmcjdZZ66bE6cWqsExwpQcVrdGQUQLIQPTrH+xoL/3xhT6xQ+gF9BTNNoY88CgOultFTW5R7BSx8oV6sTlR/brvirQfXI52jIeEMcvt8=,iv:tbkOj/w1Z2+hB/BgXtfOfcE9G16FtEe3VKCAkPp8R6I=,tag:vhVltzqz8ad+tahCHQzp8A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:KSY6Gy91xrQfPEMmIkuGodbgYucejv3iSsa/MZ4TQUB302lsgSEOPUZavCmsNZwuWVg4tqGGw0VoYZxkBTXTF/hxOokjvMqAvFF34E1l4CK5V3BFQ0Kz4bt2+UZ8kGP7xCU=,iv:U3mZhrVWCzxcjfgF2BbuOtj2F5t4ueKWqYs3r7/jpo0=,tag:zLkF5cqPaJnD/8bSCui5dg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:uo6JfILOOZHqsUTAwve9TBxhU5CZxE1dd35pL4S66/mCPp6Vh6Zf9UZAj5x6+HfrEGK+L+pkQsT3CIRMS/qd/Q==,iv:8nV8psjK961r292HhlGM04oaB+bPjheHBVmnH2ihVT0=,tag:etC4WL5Lm815NE7FHh3Jew==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUk5nRlFpZTV2YlZudTZF
            NFhtNmxyTEZQYUJUbVJuZE5ETXVqZnNZdlJjCmRCdlJZb0lPVWxic3g0bUJyZ1gv
            RDV5R1BGWTNsNW4yZ3FnQ2E3UHRqd3cKLS0tIHJWa04vN2kzQzZMazMwNVE2dSsz
            Q0MvTXFEcm4vSk16dWZjaUQvR1cyc3cK1xr0f47/AMkYLf4pYGukXeLJuJcxJArI
            V8JMQXsuXN+Osq2z4sOMuhq7cLu+aE08gcJn6As7sdshuua1BIhDIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T14:27:51Z"
    mac: ENC[AES256_GCM,data:JKhlNkUN0GAG88xUiuk9CD9llu3j4qvOnfnRnKSOcuq9qedUXf7uVVbwqfttcvbGC8bBM4EoSDd0OgZE7NFjDnPBfXeXUn2Me8lbJnOtaFjpnbiFyOG0D+TPc0IZxh4d7vR0C/SrqrSN1mKw/A8pS/kRjl0ucRyKDqJtVF6PgOs=,iv:sDCPj4gT1wIek99GxPzJWQiVjHL3+OFIAPkP3UkR+QQ=,tag:V/0zTdh7yuVPJOFtmSMfaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
