apiVersion: v1
kind: Secret
metadata:
    name: postiz-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:+v997WbjbMVOQASQfIdTp+HrNVTU0ASACxSrMlo+AnjVZX2GSSqm7yqznx37kcnF58A3GqghMAed1mLS0BDQw0YGofJIUUdKQH2dUkihmIMm7zNa2nllFm+v/RqlCRHGw4ppmb3dibtwZV1o1DvSx1jLPO33tGk=,iv:ZGg7DFuFwh38Cn9Be8F234ewIGtDWHK5GxRVXjZmXcM=,tag:IDYDlM8gkw8ol5QZiFZ1BA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:nbqqX3qkIGImLoPwlOum9XFuO6B7G79XnP86lbA6mHE8dgKEX8Y3dYuv581rTTyN+x1T1hwkmgtFcrGvE2xHqQ/+yhTzQAzyZJEd1L0oUkN94Z3ka7xtgEbFxnmNNDRNOFy8wUwSf5+b,iv:evWwQkMP+o9laOjxXqUp+MGVMiD8FBc0P95kk5mquuQ=,tag:o1kxfbACWLqLfNH6qEmsKg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:OEcBrOtc2lb7Q8UGDY6Wx+L9J18V8ETYyg6zhfm+AI8RyvaZV7AoZKYhW+yQshva7EthAuWRTmMutvY+OE6nDQ==,iv:hbOMotJ2faVl7e90Hkd14+fVs4utlwjj1C6e507Nruo=,tag:HQDLpBBY5KXg41TYExKNIQ==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd3RicWJUenhva2JkQzU4
            VUdBKzA2Z2NmMld5MEdMdXZpZm1TUEM3MUg4Cm5HenBQL2ZFUGI2SjBVVVZidmxM
            bTVQMDg0eTAxMERVMVhWM3Rvc0JBUVUKLS0tIFVJYUFqT3p2dm1Db2tVOW5veDVq
            ZUZUcjdHTmxyZjlOdUNuNWF3U203SzQKlRCiV4p156vKjb1ixbqefAmdSQafBAHn
            QMXWkJm/Ya+ffmq8n0xemThKdd1OizMQN/CpjQOF50hNzxJWW/zWzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T07:29:29Z"
    mac: ENC[AES256_GCM,data:psN9oTAvoVDRFZtjpT1lR38o9+3MTrD5GcwN2DNBBJPXUkrLERbe08ae+1CjGwPE4qhiN5k6LwlbkH4LPQnNBsqJGqrXJy2JLthDQLTLAFfj+AoB4VwESPbvQDREEnjimD+aP2TUj2yk+697dITSAfZILp5Zbu5+ZkBAfMGcRVw=,iv:DPLjMkEFr9deHcOsSNBwK198bXFdQ7STFXAELPm+U9M=,tag:Vjxk5JHPARAYQFi1bYLa2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
