apiVersion: v1
kind: Secret
metadata:
    name: postiz-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:tQ15SLToO10vChJHK8G1lzLORopn55DHePN4prnCdUAa/GCuEnCcmcjdZZ66bE6cWqsExwpQcVrdGQUQLIQPTrH+xoL/3xhT6xQ+gF9BTNNoY88CgOultFTW5R7BSx8oV6sTlR/brvirQfXI52jIeEMcvt8=,iv:tbkOj/w1Z2+hB/BgXtfOfcE9G16FtEe3VKCAkPp8R6I=,tag:vhVltzqz8ad+tahCHQzp8A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:f/cJRZco6+N7z0WAP5ukPv5eoEcmP7TNaRHt9O1JPWHUFs6zEOeWEsJ/6LyqOwRoU7kAevJCWwfC6bKKHDopomgpFY5jd6+g54yDXHnvVhd8cIMJJcT5wURj4oeIDUpDTu8AvkSQP8qE,iv:mfbto91RhtA4StAJ1AUrDZ99DAkt9Gn0+J5Y5WtpSQg=,tag:5RBVN6Ioc1OeMn0GjHRMcA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:uo6JfILOOZHqsUTAwve9TBxhU5CZxE1dd35pL4S66/mCPp6Vh6Zf9UZAj5x6+HfrEGK+L+pkQsT3CIRMS/qd/Q==,iv:8nV8psjK961r292HhlGM04oaB+bPjheHBVmnH2ihVT0=,tag:etC4WL5Lm815NE7FHh3Jew==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUk5nRlFpZTV2YlZudTZF
            NFhtNmxyTEZQYUJUbVJuZE5ETXVqZnNZdlJjCmRCdlJZb0lPVWxic3g0bUJyZ1gv
            RDV5R1BGWTNsNW4yZ3FnQ2E3UHRqd3cKLS0tIHJWa04vN2kzQzZMazMwNVE2dSsz
            Q0MvTXFEcm4vSk16dWZjaUQvR1cyc3cK1xr0f47/AMkYLf4pYGukXeLJuJcxJArI
            V8JMQXsuXN+Osq2z4sOMuhq7cLu+aE08gcJn6As7sdshuua1BIhDIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T13:02:05Z"
    mac: ENC[AES256_GCM,data:J2MVidLaQzgSxrrvHDhabFoC/sLKoX2ZH3t2GJsAczPandVVxw2oRECuFZWa6KIG1x/IQTK6pRCJtiUn8A3JzkcI3zSNnFs5ve6pSXCY+qApkAW3eq1yoW6nzSRbFvnp8N9a87mua9YTcpptqH5tmNkw2pQXaTNqJMiQJC7Rvmo=,iv:zKCstDjG3gB9tmGERjajQBHucRm3t4eS33WUU860b8g=,tag:/a3t9vL+S46vwcMLA2pGoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
