---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-lotus
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            nameOverride: immich-server-lotus
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.135.3
            envFrom:
              - secretRef:
                  name: immich-secrets-lotus
      machine-learning:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.136.0
            envFrom:
              - secretRef:
                  name: immich-secrets-lotus
    service:
      main:
        controller: main
        ports:
          http:
            port: 2283
      machine-learning:
        enabled: true
        controller: machine-learning 
        ports:
          http:
            enabled: true
            port: 3003
    persistence:
      photos:
        existingClaim: lotus-nfs
        globalMounts:
          - path: /photos
            readOnly: true
      storage:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /usr/src/app/upload
            subPath: Lotus
      config:
        enabled: true
        type: secret
        name: immich-config-lotus
        globalMounts:
          - path: /config.json
            subPath: config