apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
  labels:
    goldilocks.fairwinds.com/enabled: "true"
