---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            nameOverride: immich-server
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.110.0
            command:
              - "/usr/src/app/start.sh"
              - "immich"
            envFrom:
              - secretRef:
                  name: immich-secrets
      microservices:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.110.0
            command:
              - "/usr/src/app/start.sh"
              - "microservices"
            envFrom:
              - secretRef:
                  name: immich-secrets
      machine-learning:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.110.0
            envFrom:
              - secretRef:
                  name: immich-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 3001
      microservices:
        enabled: true
        controller: microservices
        ports:
          http:
            enabled: true
            port: 3002
      machine-learning:
        enabled: true
        controller: machine-learning 
        ports:
          http:
            enabled: true
            port: 3003
    persistence:
      photos:
        existingClaim: photos-nfs
        globalMounts:
          - path: /photos
            readOnly: true
      storage:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /usr/src/app/upload
            subPath: Immich
    ingress:
      main:
        enabled: true
        hosts:
          - host: "immich.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: immich-main 
                  port: 3001
