---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 3001
        runAsGroup: 3001
        fsGroup: 3001
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:
          main:
            nameOverride: immich-server
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.5.0
            envFrom:
              - secretRef:
                  name: immich-secrets
      machine-learning:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.5.0
            envFrom:
              - secretRef:
                  name: immich-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 2283
      machine-learning:
        enabled: true
        controller: machine-learning 
        ports:
          http:
            enabled: true
            port: 3003
    persistence:
      photos:
        existingClaim: photos-nfs
        globalMounts:
          - path: /photos
            readOnly: true
      storage:
        existingClaim: scratch-nfs
        globalMounts:
          - path: /usr/src/app/upload
            subPath: Immich
      config:
        enabled: true
        type: secret
        name: immich-config
        globalMounts:
          - path: /config.json
            subPath: config