---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      immich-web:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-web
              tag: v1.84.0
            env:
              TYPESENSE_ENABLED: false
              IMMICH_SERVER_URL: http://immich:3001
      immich-proxy:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-proxy
              tag: v1.84.0
            env:
              IMMICH_WEB_URL: http://immich-web:3000
              IMMICH_SERVER_URL: http://immich:3001
      main:
        containers:
          main:
            nameOverride: immich-server
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.84.0
            command:
              - "/usr/src/app/start.sh"
              - "immich"
            env:
              TYPESENSE_ENABLED: false
            envFrom:
              - secretRef:
                  name: immich-secrets
      microservices:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.84.0
            command:
              - "/usr/src/app/start.sh"
              - "microservices"
            env:
              TYPESENSE_ENABLED: false
            envFrom:
              - secretRef:
                  name: immich-secrets
      machine-learning:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.84.0
            env:
              TYPESENSE_ENABLED: false
            envFrom:
              - secretRef:
                  name: immich-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 3001
      web:
        enabled: true
        controller: immich-web
        ports:
          http:
            enabled: true
            port: 3000
      microservices:
        enabled: true
        controller: microservices
        ports:
          http:
            enabled: true
            port: 3002
      machine-learning:
        enabled: true
        controller: machine-learning 
        ports:
          http:
            enabled: true
            port: 3003
      proxy:
        enabled: true
        controller: immich-proxy
        ports:
          http:
            enabled: true
            port: 8080
    persistence:
      photos:
        existingClaim: photos-nfs
        globalMounts:
          - path: /photos
    ingress:
      main:
        enabled: true
        hosts:
          - host: "immich.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: proxy
                  port: 8080
