apiVersion: v1
data:
    DB_HOSTNAME: ENC[AES256_GCM,data:D0dyKDfEu1S3rZE3DoCwhgDWOIhOXr2HKH0e5pOcfClnCDjmFJw/Kq84qpJOHn3i,iv:Eak0RwE8byGr2dyb8cFbwAtrLpn3hOzBjUTG/8us7z4=,tag:XpIxYxdMBeOK4m1gB+2OtQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:RFSUUSwsMOc=,iv:CJdMdbvYNhuObFqCiqMxIa4Fx7GdunDtH99JUprUoCU=,tag:At5WSWoa1QWDWp/HRieEAg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:xDhXtNi0wvitZ/cVXebRRhnMwQk=,iv:yiWdN6S8+XpZQDPMdcR3xm7fL2fkurWYsl3Kjk1WY+E=,tag:ntO/wfa4TmlDrDsKTNlA4A==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:MjGvNDbrOkY=,iv:SNXp1LbgmAvtevY4NZddESpNxBm/v8FqCpDRPgxXEsQ=,tag:rIuWPJEdGWE4YIF7qyZCYA==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:wWT9KUQqo1WYpWOF1E25fcC1wvLiKhy93juDsoj8dNj/RmZw+XDUsw==,iv:OrT4YYBvkab8M83G9k8lBM27tvDMLoHJby53slllkzM=,tag:5eGphRS2l2STJXhtUI9vVQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:kfngPt/8IvXI7mXOKziwlA==,iv:JVIMvYl+1TCS9QhETt2QnWF7/0trbg4IEV/rIVaKX+4=,tag:7flG0xEyKjYGyb7PhL+hUg==,type:str]
    IMMICH_CONFIG_FILE: ENC[AES256_GCM,data:u/SYYnTF3EGAjiuD4uMohg==,iv:jaXsIjk4jI9hw/WydX1AGYXRDZfhcKlLEzolY1EyRn8=,tag:qqtkW3vLYkwPjGUHl/8bNw==,type:str]
kind: Secret
metadata:
    name: immich-secrets
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bCs4QThvS1N1UFlSWmpp
            UStxc1pNeU5ETmlIZ1l2Yy9xRkdoSlJmWmpRCkJJd3Jpb0Q4ZFVjblBuMzRNNHJP
            ckMrSnJBRE92UTgreFVmRHB5b3NhTlUKLS0tIEoxM2hNVEd1TDJGajhva3EyV05s
            eEhOdmhJMFJlbW4zRnJwbUVDdHErYmcKH1yCdGdtSqerlYQN8NCNHSHyph+Mehww
            IcIoRV4dMx+r3i2DZ43qsUnodb+u/GNQeU8UjskWANgQAUEcK2bTuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T15:28:38Z"
    mac: ENC[AES256_GCM,data:itetrz7VYYs9iHeRmWMM46u9M0IdlML1OSQUSAlCkbG8rpAA6ftdD50ouHW8C35+Ac9Ygpk8r9KaM/QIMLJfKq7ECXwOHIxLycvnByVcSnx+0CkBdXcC++YhIqfz3kROGT8X/L/0g9f11SzhX7SZHXJjp85NCTfg2jd4SDiHrr0=,iv:s0kbwlwGzGE1gh/pYANVsWOwqlMuO6KI/X/hX4TORWc=,tag:iw9CCCIAzCajRd/Pk++HoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
