apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: longhorn-backup
