---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.1
            securityContext:
              runAsUser: 0
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8080
    persistence:
      main-config:
        existingClaim: sabnzbd-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: media-download
        globalMounts:
          - path: /downloads
    ingress:
      main:
        enabled: true
        hosts:
          - host: "nzb.${PUBLIC_HOSTNAME}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 8080
