apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:nDn78nzBNQfBsTCebxkfeBju0/67hdHO6ZXkmmH+rt4=,iv:Bfu/Q3xZQMDmFCMjAjO7wNN2G6RKh1KCwfSYnCSU64s=,tag:gBiqKAG7nnWm7l1TyT6p0w==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:PRI2DD2otDl4txqjuf6fWaAG5EQgr4xJMT3Zqb5LI2I=,iv:Z3DGSnrroDVZNxcbySNjC49KjAtCXX5zlKKOjaTQCXg=,tag:poUGi/MP2XqFj58xz1Vlxw==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRGliQ2o4cmtSQ0VpV0FJ
            a1h5cmpoMU90Vjhmc1dia0Y2d1cxMkNOOVdRCkdadzd5ajlFV3cxRUJxQ2E5aE9o
            Nm5Eb2hWbU5FSEN6T3FOMUpYQzdPanMKLS0tIExGa250VEZvTkVidTFXWXJoSzJz
            ZmNIaVFZbjdTOHpkK3Rmd3V6Nnl4dFEKwEb3V5IlRA6lRzTl9pEXXUFbnzd/D3m7
            SkAKQKuVOKrHYiUFDDwa2oO0/ZYTH+Dnof2+BQEPvbPAHGMVsiEqjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T23:36:52Z"
    mac: ENC[AES256_GCM,data:kMI+TZ8LCIdYaeodOf1EfEQJEeA+QohCGfeHY8LZ3t9dNnkU+AMvTw+QQRkO/GD2gFQcDitX648PwRIyeyncmNHuAO7trfiL+B36BP3jSZJveLPI+cOSIraeeZYApFsOt//kvLIyvC0KsRxkJlrVvIoRH/AN/QUVr9pgry/2F/A=,iv:lE/uuhkG5NgpRrdtjAk7ZE/rY8l8AFLWiKDb9xvDixI=,tag:IrQHdNEvpGrfbLjsAkZO7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
