---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-intel
spec:
  # renovate: datasource=docker depName=quay.io/kairos/ubuntu
  version: 24.04-standard-amd64-generic-v3.3.1-k3sv1.32.1-k3s1
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: NotIn
        values:
          - "true"
      - key: kubernetes.io/arch
        operator: In
        values:
          - "amd64"
  cordon: false
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
    disableEviction: true
  upgrade:
    image: quay.io/kairos/ubuntu
    command:
    - "/usr/sbin/suc-upgrade"
