---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-intel
spec:
  # renovate: datasource=docker depName=ghcr.io/bidluo/ubuntu-hw
  version: 23.10-standard-amd64-i915-v2.5.0-k3sv1.29.0-k3s1-c0.1
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: NotIn
        values:
          - "true"
      - key: kubernetes.io/arch
        operator: In
        values:
          - "amd64"
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: ghcr.io/bidluo/ubuntu-hw
    command:
    - "/usr/sbin/suc-upgrade"
