---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-intel
spec:
  # renovate: datasource=docker depName=quay.io/repository/kairos/ubuntu
  version: 23.10-standard-amd64-generic-v3.0.5-k3sv1.29.3-k3s1
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: NotIn
        values:
          - "true"
      - key: kubernetes.io/arch
        operator: In
        values:
          - "amd64"
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: quay.io/repository/kairos/ubuntu
    command:
    - "/usr/sbin/suc-upgrade"
