---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-intel
spec:
  # renovate: datasource=docker depName=quay.io/kairos/kairos-ubuntu
  version: v2.0.0-rc7-k3sv1.26.3-k3s1
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: NotIn
        values:
          - "true"
      - key: kubernetes.io/arch
        operator: In
        values:
          - "amd64"
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: quay.io/kairos/kairos-ubuntu
    command:
    - "/usr/sbin/suc-upgrade"
