apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
spec:
  # renovate: datasource=docker depName=ghcr.io/bidluo/ubuntu-nfs
  version: 24.04-standard-amd64-generic-v3.3.1-k3sv1.32.1-k3s1-iscsiv1.0
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: ghcr.io/bidluo/ubuntu-nfs
    command:
    - "/usr/sbin/suc-upgrade"
