apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:rg9c3C5C3rxyDdLxiKw0KBRrbzpfy7V1p5Uk28s8Y+WBiH9tVQgV6ZHlemggYwbQ,iv:pm+Db9OWZ4/0lCvHm3O4XwUIF5pBNhY0GCvbVLyUTsg=,tag:VPl4vvitf9BsVD9XLfIMAw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:aY4dVW/rgIoY9sy3sMRlmoQNYJlN8nJTTGyQ1+z2TZTmghqbMBwffvS8lpEMcGiXni7nE/xrBmMKUXRJgQpYkQ==,iv:Iznn3/7z9gq/WaS+Hm+DyoB9MVBVqIT8w5YCTAIcS5A=,tag:tsowKd8PlBMHFfokpHaXPg==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:2caBB8V3qZCBQTc6u/PdxKYS7lS2g5YpZuSvon1jjncyVihvqErU284SufvGX/Fmb3XZX8zbct+X1Bn5eO+mgmyWxOhyEfd1TwOjiOTxBnvau+X0fj+96q8xGymxze8xdwCG/og=,iv:RrZXno/N5crcxZNDoP/ibVKmFMNYgWPSo6s3tdkAf5I=,tag:lvNt0dN/rbd9cZxHB5AOXA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:ZZMyMCw=,iv:mROge4heF8xb/YWFIpjCFIXUJTrSXD1Iw4DsSuXit4s=,tag:2QCEopqEKiR98qB1sSU1Nw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:WphChLVdiNCIbZv+hbfWmhJBH9A=,iv:mWgdItyav3hMHGNtoFywHegVaSkZ6cpllM6VRNn2MF8=,tag:x8yTFFzzqVRxqAUci9YKdA==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L1ZjV0pGTVQ5enhuUHRx
            QytZRHc0WVYvdEZrNnE3aVptM1ZGUk9vWUhJCnBadnhqK0UrK0lUUVFncHk5WDFs
            K2QwQjQ3M04zb3Q0OFB2V1JpUEFINXcKLS0tIDNub0NsVHlMTVVQYlRjbUdoRnVI
            QlFmMTgxMVFuTkVxUFR6WjBqNE9sbjQKVZlrwisXLhJ8Ez6TcdpStIs1Z0QEwHFv
            ITWsHIF6UM/GGPYWp5zOazLURljQe/WjrRl83Q5fDFDrSBTdQpqoqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T14:27:51Z"
    mac: ENC[AES256_GCM,data:dsmajpvqLz1TrYeaE5jkLsKgsOdUTnsPhfbL2vHtPXIaouqj7ZC6BisByuBzOSB4W4f+14fp4YDdH3GyP838vxUoF0AYe/mxx6BfFZ3nFxpABNZJBMo9LXwKU2LkUkOFLSPjODwfkf1S1I2Ma2oP5TnW6j0zLyNXbahT56kIulI=,iv:MCPzuEUIx0BHm1keQkQnxMw7St90FmMwS5+eq3T3+GA=,tag:pnmA/jCAyuhB9arSweYK0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
