---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: n8nio/n8n
              tag: 1.89.1
            envFrom:
              - secretRef:
                  name: n8n-secrets
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: 5678
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: &host n8n.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: n8n-data
        globalMounts:
          - path: /home/node/.n8n 