apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:guuefXIc3W/PZAI5T6iJsy9idNmI0mQtHXc/axOpBjv7nw84bBpRmbdUE2SgZ6Cb7D9xEnpIaKzbcpkKDK6NJ6zj/n6uBZCQ7fDacod+2KQ12Kjm1uxchZ9Jlv4Yih1X3i7gfpWwLHXSJtzl,iv:IBFlnlkOeuVzS8Nkx0SxBAkmK0pl1Uf4j9fosOuyHm0=,tag:uJmwENEFZ/jazxMnNzawsw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:JhmBSM8tmFMmJVyBSZ6v7M9y6hggKuj+szTEX7tHqT2kFIpa0qqdYNNHFLYqPUuGnHCSVu6X8HPRLtrHyUj8ZrlnVTHMLD32bGTjQNclzDJZ+8KFu9A4Tx74TCp7GRTSTPEpMY0cqxYwKJj9EN7YVh4tvnJsdB3venOse800xIqHR3z+OPJr+2P/Ltz6BRsdhNY+592pP5sEFMtrcTvSJKxj54M=,iv:XB3LUNygGkyYnhqVaxRSaILYYqz82jWhkicl2bkVl/E=,tag:h6CWZFOXhPeMCnAdiEFlBw==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeWQwb3pYUXhOQ0RpYXBS
            YURpakdjNGV1cVVwdFI4QXhtd2pNMUd0K0dBCjhUTVVHbm1DYVkrM1UyOGI5RTRG
            aWd4ZDBXMDF2TUJrR1RqUURMaTRxMHMKLS0tIHROcXNMYWRJV1QzblVrRVB6ZUZo
            d1MyYVUwWHVIWUJmRFBxN2FEYjF6R0UKpp0ZsNR5b/yN3LIkzUgcOwnGZVhAZYkh
            xACO0CZEioPWfH/Gi73dN6dWGtwDd3/TzR8hf8mhcduyYbziWGbenA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:50:49Z"
    mac: ENC[AES256_GCM,data:Rsd8fU4VMq18jACIdW5fw1jxC9KVFbgUnXcKffGuTBPRJJeCi0zcSbMgtj+eBrXQeuVfHRaWMOFjtF+fUNRWXWOmReyFW78IUVqDw8hccEJ4hUN6obSyuqEsu8GBVVzLYzMnJlaCld1ZT9MrdP7rGeqTJAkBkOn7P4xzHbfW5HU=,iv:f/MG6SPf42fxxxNMiz9pq19GqGl6psVG/Ck2moimXCY=,tag:a+kW2pHn4DnfdwHGBPrTcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
