apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:wS1gqBAwBrbkVNrVF2idO/o3FHmbap5L1RXYM0H59qB6b0vTn3gh593nemGnED40pDRBNQTCM9fled/Sw3uHMManFAtJsBXship+xlRgHOU5CVP7i5dzZV6Ksu2RdHqLWYAo2e/Ks6NBBXAr,iv:Hy3IIOpkodARn3QdkuyJihEjBGUMkYc9RxhbsUwno2s=,tag:JgVKgCBcQD/3d7JzAwCTLA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:xXJ30DNov93RuWnzV8FCcB7DLbOgke4X6Ww23TsgSeW9w2a3idR6znMe/OrBzj77QVDw5sAfusZBZ3L1rA1en2BN+hKiyD66z9gbBiyHK5TfiK3WB72+886kb1Wo2BXcWP9xx0hR/P/LbdVQRxH1wjId6y8tx+qI2RdR03Yyw98hVtDxgeXBSjPtTIEQ8kXoQ2pwAJg1/vVy7tFPe1vdHZgWUr4=,iv:5itBum+MnvzfEXOYvpzDTGgVwZKW8vXBL5SFC7dOaPc=,tag:8/XN7i86a4KtksOEftVsKQ==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSG5Ycis1ZGxXUWcwT1hi
            aTVXbHZXNitZTENtd3dwV3ZMTmFkTVI2aWowCmV2TkdJTzgwaFhsR3NMVmFVSzZM
            YXNwOWhBKytSRXJ3SmJydklMWCtEeHMKLS0tIG9STEFKMU51NjV5NTMwQ2Vselk1
            VTVBWHp3aEJac2lFbkY0WDhJR3hzTDAKrF2OxPPGjuFWduK5ggt8GmuhhvAIaXfg
            asGkU4N3QjVkp+lKni+7HNs1R3iQu5W7VXXAXs/ACacellU8MvWOhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:58:43Z"
    mac: ENC[AES256_GCM,data:ZDp6IKna7Ar+651RIabuJIwC1PdOYAfn2yYcsCjcm+6AfBMMIXcJy75rbVEUpnPZsF/e44pGjjzJ/P30m2bydsZAiCkcRJulp14KRnPCP86dHSxxK1ET5buANZqDT5f9vheOmv4seGMOwgjPiL3ZzLRP9r/paDXXSpYPhXRoBVA=,iv:cP1KwquNVytGsfSVahpRG06iMgnxJQfuyS1pkJDVmwk=,tag:9Rr4H6eCzpKz+rmhVIBd9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
