apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:v0j5Bm2XGEl5tZev0NPORNE2mF+D6LvnvZThM8kZM1IK/WbQLy/NXNHe4H7LOu6qmGWoO4+Ipitfj2w/p7mqbtiLW4KmKClD3Pc3ICfIXdRNqB6A18OzaZ9nZWY0h/QTUF4g83WXLY+1RqFKNJLEut1Pzh28MQ4dpXs942g5Ial9uMXBj4/wvB1iXbVyBq4l,iv:bYlI9G3a81Xh/jwkdggKWgvUtnouTZHVP9oeFGsbjq4=,tag:fm0lWK4Nm0Dw8RPB/SdYCA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:6sbDDSD6dFloUQvK3WJZTbePE/wmD6Dohvhqfw/mPoABDFjysyw6+9gdofySYDfE8Gykw0nzR056lUQjMtZv5VwKXTdAOYjgv7I5WV2Na0qw8PuOoVCf+CxEQ5ndJqwpipy052lXICYpduyotpTFggfL54i2F/gIJl4fXUsuM42XUpC2DoZPxJi39qZEjtxwzaUcl2qSS0vsXkNsIwLkzSexf46+sTcLtbLwQRW3L1R2TaCWDsX1rVn+sUi18WWfWeFEm2+PEwXPVCHlzbCWSu+UjwDjD3aCpPxqcg==,iv:5sdFUFSqmuq6P2AShUGetFa08mtTJAAcWCyM8Ykdl6s=,tag:r4teXzWEso9r2hFkoxLA0g==,type:str]
sops:
    age:
        - recipient: age1mt3e0vdhgcxtcqfv0jhfdeejkk8f48elacyua387nekmnfufsd4qhtwmqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN25HZDBXMlExMEY1MFg1
            dkJWS24xOGFyNDRmU3Q3dVVVRCt1L2M0TVV3CnRNU25MSWxXSTkzN1RKcEtzSTdG
            a3h1aGVsbDJndjNLOVc2T1N0MmZFWjAKLS0tIHNUV0M5L005dWlxQTBjMER6eklU
            Wk8wcGR2Rk1zWXVOUEgrTmtYVVI3ZzgK64NpGSoqWwS2aesxDHL/74b680WDnSag
            bZz0+2ZX9lkzIKSSKZjFnUiqT7ucZJ0i+R0TfdALorHwN6KGQadXlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T04:17:42Z"
    mac: ENC[AES256_GCM,data:9mJ0Fn5X8sxiOzyjj/JNwmefwucH0AC5jedY1DLB1xdlKLQeralsF6pOotecIQnDro2q3ecuq0OTbCkQ0Tog78LUAIT25fFaVCdMps1f3oI/zGFs6YDx8qaZzztYD1swWiAUSpuraXq3HZZB+7VBDOnXknvjR4xMmsvGlnhPnwI=,iv:SNfbiSsmw9F9ApdfdXBE9OCISffzKs657XWKgVdAYzQ=,tag:/XUpJB/F8Xsy5DUtaXe95A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
