name: Create Helm Diff

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/**/*.yaml"

env:
  conf_live_branch: main

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get changed YAML files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            yaml:
              - added|modified: "apps/**/*.yaml"

  helm-diff:
    runs-on: ubuntu-22.04
    needs: detect-changes
    if: needs.detect-changes.outputs.yaml_files != '[]'
    strategy:
      matrix:
        file: ${{ fromJson(needs.detect-changes.outputs.yaml_files) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Checkout Live Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.conf_live_branch }}
          path: live
      
      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: "helmv3 yq"
      
      - name: Diff Helm Releases
        id: helm-diff
        run: |
          # Extract information from HelmRelease manifest
          hr_chart=$(yq e .spec.chart.spec.chart ${{ matrix.file }})
          hr_chart_source=$(yq e .spec.chart.spec.sourceRef.name ${{ matrix.file }})
          
          # Find the chart URL
          hr_url=$(yq e .spec.url charts/$hr_chart_source/*.yaml)
          
          # Extract chart versions
          hr_live_version=$(yq e .spec.chart.spec.version live/${{ matrix.file }})
          hr_pr_version=$(yq e .spec.chart.spec.version ${{ matrix.file }})
          
          # Exit if versions are the same
          if [ "$hr_live_version" = "$hr_pr_version" ]; then
            echo "Versions are identical, skipping."
            exit 0
          fi
          
          # Add the chart repository
          helm repo add pr "$hr_url"
          
          # Diff Chart.yaml
          chart_diff=$(helm show chart pr/$hr_chart --version $hr_live_version | diff -u - <(helm show chart pr/$hr_chart --version $hr_pr_version) || true)
          
          # Diff values.yaml
          values_diff=$(helm show values pr/$hr_chart --version $hr_live_version | diff -u - <(helm show values pr/$hr_chart --version $hr_pr_version) || true)
          
          # Format and output message
          message="**Helm Diff for $hr_chart**\n"
          message+="\n\`Chart.yaml\`:\n"
          message+=$(echo -e "```diff\n$chart_diff\n```")
          message+="\n\`Values.yaml\`:\n"
          message+=$(echo -e "```diff\n$values_diff\n```")
          echo "::set-output name=message::$message"
      
      - name: Find Existing Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Helm Diff

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        if: steps.helm-diff.outputs.message != ''
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.helm-diff.outputs.message }}
          edit-mode: replace