---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.7.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  values:
    vpa:
      enabled: true
    dashboard:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: null
          memory: null
    controller:
      resources:
        limits:
          cpu: null
          memory: null
