---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  path: ./apps/monitoring/uptime-kuma/app
  targetNamespace: monitoring
  interval: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: uptime-kuma
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: uptime-kuma
      namespace: monitoring
